### ISSUE TITLE
[Bug] DLL load failed

### ISSUE THREAD

**Issue by Lazurite12** [deezer/spleeter#105]
## Description

I tried to convert a .mp3 file, which was inside of the same folder as spleeter and python. I got the error message, "DLL load failed: A dynamic link library (DLL) initialization routine failed."
## Step to reproduce

1. Installed using `ffmpeg`
2. Ran 'spleeter separate -i juice_wrld_lucid_dreams_dir_by_colebennett.mp3 -p spleeter:2stems -o splits'
3. Got `DLL load failed: A dynamic link library (DLL) initialization routine failed.` error
## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```
Traceback (most recent call last):
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.4.3', 'console_scripts', 'spleeter')()
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 47, in entrypoint
    main(sys.argv)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 31, in main
    enable_logging()
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | pip|
| RAM available     |8 GB|
| Hardware spec     | Intel (R) Core(TM) i5 CPU    750 @ 2.67 GHz 2.67 GHz |

## Additional context

I followed Dylan Tallchief's tutorial, "https://www.youtube.com/watch?v=tgnuOSLPwMI"

**Comment by Lazurite12** [comment]
I also tried putting apostrophes around the file, and used "-p", but nothing worked.

**Comment by Faylixe** [comment]
The DLL error is related to Tensorflow, sound like your installation is invalid. We do not provide assistance for external youtube tutorial. Please follow the wiki for installation or go to [Gitter](https://gitter.im/spleeter/community) channel to ask for assistance.
