### ISSUE TITLE
[Bug] Spleeter doesn't work after extracting downloaded pretrained model

### ISSUE THREAD

**Issue by sillycalvin** [deezer/spleeter#107]
## Description

When executing the script and after it has just downloaded and is extracting the pretrained model, it then throws me an error which Ive tried now for the past hours to fix to no avail.

## Step to reproduce

1. Installed using `Anaconda or Pip, I've tried reinstalling anaconda aswell and clearing some stuff in path`
2. Run as `spleeter separate -i audio_example.mp3 -o outpu`
3. Got `ValueError: Operands could not be broadcast together with shapes (2, 1024, 126) (512, 1024, 2)` error

## Output

```bash
(spleeter-gpu) C:\Users\root\spleeter>spleeter separate -i audio_example.mp3 -o output
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
Traceback (most recent call last):
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\root\Anaconda3\envs\spleeter-gpu\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\__main__.py", line 47, in entrypoint
    main(sys.argv)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\__main__.py", line 41, in main
    entrypoint(arguments, params)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\commands\separate.py", line 178, in entrypoint
    output_naming=output_naming)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\commands\separate.py", line 132, in process_audio
    for sample in prediction:
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 619, in predict
    features, None, ModeKeys.PREDICT, self.config)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\model\__init__.py", line 392, in model_fn
    return builder.build_predict_model()
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\model\__init__.py", line 334, in build_predict_model
    output_dict = self._build_output_dict()
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\model\__init__.py", line 130, in _build_output_dict
    self._params['model']['params'])
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\model\functions\unet.py", line 173, in unet
    return apply(apply_unet, input_tensor, instruments, params)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\model\functions\__init__.py", line 26, in apply
    params=params)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\spleeter\model\functions\unet.py", line 161, in apply_unet
    output = Multiply(name=output_name)([up7, input_tensor])
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 591, in __call__
    self._maybe_build(inputs)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1881, in _maybe_build
    self.build(input_shapes)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\tensorflow\python\keras\utils\tf_utils.py", line 295, in wrapper
    output_shape = fn(instance, input_shape)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 111, in build
    output_shape = self._compute_elemwise_op_output_shape(output_shape, shape)
  File "d:\users\root\anaconda3\envs\spleeter-gpu\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 82, in _compute_elemwise_op_output_shape
    'together with shapes ' + str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (2, 1024, 126) (512, 1024, 2)
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 |
| Installation type | Conda / pip |
| RAM available     | 16 |
| Hardware spec     | 1060 6gb / Xeon E3 1231 v3 |

**Comment by vonsovsky** [comment]
At my computer it helped to change channels_first to channels_last in %APPDATA%\.keras\keras.json.
