### ISSUE TITLE
FileNotFoundError on basic spleeter separate

### ISSUE THREAD

**Issue by Telergoel** [deezer/spleeter#134]
I was just trying out the following simple command line:

`C:\Users\Léo\Downloads>spleeter separate -i celine.mp3`

It unfortunately fails for me due to a FileNotFoundError. I made sure celine.mp3 does exist in Downloads though. Any idea what could cause it? Here's the stack trace (most recent call last):

```
  File "C:\Tools\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.4.5', 'console_scripts', 'spleeter')()
  File "c:\tools\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\tools\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\tools\lib\site-packages\spleeter\commands\separate.py", line 43, in entrypoint
    synchronous=False
  File "c:\tools\lib\site-packages\spleeter\separator.py", line 122, in separate_to_file
    sample_rate=self._sample_rate)
  File "c:\tools\lib\site-packages\spleeter\audio\ffmpeg.py", line 63, in load
    probe = ffmpeg.probe(path)
  File "c:\tools\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\tools\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\tools\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

Thanks for your time (and for this amazing library!!)

**Comment by sai-krishna-msk** [comment]
similar issue, I tried giving both absolute and relative path but I get the same error of file not found

`Traceback (most recent call last):
  File "run.py", line 7, in <module>
    waveform, _ = audio_loader.load('audio_example.mp3', sample_rate=sample_rate)
  File "C:\Users\saima\Anaconda3\lib\site-packages\spleeter\audio\ffmpeg.py", line 63, in load
    probe = ffmpeg.probe(path)
  File "C:\Users\saima\Anaconda3\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\saima\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\saima\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file `specified``

**Comment by Faylixe** [comment]
Please read the wiki for proper installation, you do not have ffmpeg installed. Plus your issue does not respect the provided template. Closing.
