### ISSUE TITLE
Error when separating on Windows

### ISSUE THREAD

**Issue by s6ven** [deezer/spleeter#166]
Anytime I attempt to separate using 'spleeter separate -i (filename) spleeter:2stems -o output'
I'm met with this:

Traceback (most recent call last):
  File "C:\Users\III\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.4.8', 'console_scripts', 'spleeter')()
  File "c:\users\iii\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\iii\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\iii\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 43, in entrypoint
    synchronous=False
  File "c:\users\iii\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 123, in separate_to_file
    sources = self.separate(waveform)
  File "c:\users\iii\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 86, in separate
    predictor = self._get_predictor()
  File "c:\users\iii\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 58, in _get_predictor
    self._predictor = to_predictor(estimator)
  File "c:\users\iii\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\estimator.py", line 70, in to_predictor
    latest = str(sorted(versions)[-1])
IndexError: list index out of range

I'm not quite sure what to do here, I've tried using pip and Anaconda. Anaconda gives a different error entirely and I've already uninstalled that and went back to trying manually downloading python and ffmpeg. Any help would be appreciated.

**Comment by s6ven** [comment]
Edit: I messed up describing the error, I am correctly typing the command as shown on the main page: 'spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output'
Still no use, same messages are given.

**Comment by aidv** [comment]
does a shorter length version of the audio work?

**Comment by starfilth** [comment]
I am encountering the same error

**Comment by mmoussallam** [comment]
Similar to https://github.com/deezer/spleeter/issues/154 try the command `python -m spleeter separate` instead of `spleeter separate`
