### ISSUE TITLE
[Bug] Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by koutoftimer** [deezer/spleeter#169]
## Description

Unable to separate.

## Step to reproduce

1. Installed using `pip`
2. Run as `python -m spleeter separate -i out.mp3 -o out`
3. Got "Failed to load the native TensorFlow runtime." error

## Output

```
Traceback (most recent call last):
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Ruslan\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL).


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type |  pip  |
| RAM available     | 8G                             |
| Hardware spec     | CPU       |

## Additional context

I'm not sure what can effect this issue.

**Comment by koutoftimer** [comment]
As far as I can say right now, it is purely [tensorflow's issue][1]. Maybe you should add it to your installation notes.

[1]: https://github.com/tensorflow/tensorflow/issues/31033#issuecomment-515130034

**Comment by HansHermann123** [comment]
I have the same issue and no idea how to get around it.

**Comment by koutoftimer** [comment]
@HansHermann123 I have provided link to tensoflow's issue traker, read it carefully.

**Comment by HansHermann123** [comment]
Ahh thanks very much. I wasn't really sure what your above post meant but now I do :-)
