### ISSUE TITLE
5 stems trained model not installed?

### ISSUE THREAD

**Issue by maaagdonals** [deezer/spleeter#189]
I tried dividing a song into 5 tracks, but it says that the trained model for 5 stems wasn't found. Is there anywhere where I can download it?

(trackspleeter) PS C:\Users\User\desktop\ai's\spleeter-master> python -m spleeter separate -i "C:\Users\User\Desktop\Music\01 Barba Azul.mp3" -o C:\Users\User\Desktop\Audio_Tracks\Spleeter -p spleeter:5stems
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\trackspleeter\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\Anaconda3\envs\trackspleeter\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\desktop\ai's\spleeter-master\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\User\desktop\ai's\spleeter-master\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\User\desktop\ai's\spleeter-master\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\User\desktop\ai's\spleeter-master\spleeter\commands\separate.py", line 43, in entrypoint
    synchronous=False
  File "C:\Users\User\desktop\ai's\spleeter-master\spleeter\separator.py", line 123, in separate_to_file
    sources = self.separate(waveform)
  File "C:\Users\User\desktop\ai's\spleeter-master\spleeter\separator.py", line 86, in separate
    predictor = self._get_predictor()
  File "C:\Users\User\desktop\ai's\spleeter-master\spleeter\separator.py", line 58, in _get_predictor
    self._predictor = to_predictor(estimator)
  File "C:\Users\User\desktop\ai's\spleeter-master\spleeter\utils\estimator.py", line 66, in to_predictor
    estimator.export_saved_model(directory, receiver)
  File "C:\Users\User\Anaconda3\envs\trackspleeter\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 732, in export_saved_model
    strip_default_attrs=True)
  File "C:\Users\User\Anaconda3\envs\trackspleeter\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 827, in _export_all_saved_models
    self._model_dir))
ValueError: Couldn't find trained model at pretrained_models\5stems.

**Comment by mmoussallam** [comment]
Hi There,

Please read the FAQ section about this issue. Good luck
