### ISSUE TITLE
[Bug] existing file

### ISSUE THREAD

**Issue by mickmiminape** [deezer/spleeter#203]
## Description

from yesterday or so whenever i try to separate any file it says that the file is existing and that it could  not creat a file when existing "though it does not exist"

i get this error `Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\spleeter\audio\ffmpeg.py", line 108, in save
    os.makedirs(directory)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'parast\\twet`

## Step to reproduce

1. Installed using `pip install spleeter`

2. Got `Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.4.8', 'console_scripts', 'spleeter')()
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    separator.join()
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\spleeter\separator.py", line 68, in join
    task.get()
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
FileExistsError: [Errno 17] Cannot create a file when that file already exists: 'parast\\twet'` error

## Output

```bash
FileExistsError: [Errno 17] Cannot create a file when that file already exists
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 |
| Installation type |  pip |
| RAM available     | 12tgo                             |
| Hardware spec     | gtx1050 / core i7 8550u |

**Comment by mmoussallam** [comment]
Hi @mickmiminape 

What is the command you're trying to execute ?

**Comment by beq219** [comment]
I get this issue too sometimes when I use the command line with -p spleeter:4stems. I can work around it by deleting the output folder (parast in @mickmiminape case) and running the command again.
