### ISSUE TITLE
[Bug] spleeter-gpu is unusable out of the box

### ISSUE THREAD

**Issue by SamusAranX** [deezer/spleeter#219]
## Description

I tried, once again, to get spleeter running on the GPU, but I just can't do it.
I never directly worked with TensorFlow or any other ML software package, so I can't even begin to debug this.

## Step to reproduce

1. Install CUDA 10.2 on a fresh, fully up-to-date Windows 10 installation
2. Install Miniconda
3. Install spleeter-gpu using `conda install -c conda-forge spleeter-gpu` in the Anaconda Prompt
4. Run `spleeter separate -o Spleeter -m -p spleeter:2stems-16kHz -i "audiofile.m4a"`

## Output

```bash
Traceback (most recent call last):
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv2d_7/Conv2D}}]]
         [[strided_slice_25/_309]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv2d_7/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Miniconda3\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\commands\separate.py", line 43, in entrypoint
    synchronous=False
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\separator.py", line 123, in separate_to_file
    sources = self.separate(waveform)
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\separator.py", line 89, in separate
    'audio_id': ''})
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\contrib\predictor\predictor.py", line 77, in __call__
    return self._session.run(fetches=self.fetch_tensors, feed_dict=feed_dict)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node conv2d_7/Conv2D (defined at c:\users\user\miniconda3\lib\site-packages\spleeter\utils\estimator.py:71) ]]
         [[strided_slice_25/_309]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node conv2d_7/Conv2D (defined at c:\users\user\miniconda3\lib\site-packages\spleeter\utils\estimator.py:71) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'conv2d_7/Conv2D':
  File "c:\users\user\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Miniconda3\Scripts\spleeter.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\commands\separate.py", line 43, in entrypoint
    synchronous=False
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\separator.py", line 123, in separate_to_file
    sources = self.separate(waveform)
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\separator.py", line 86, in separate
    predictor = self._get_predictor()
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\separator.py", line 58, in _get_predictor
    self._predictor = to_predictor(estimator)
  File "c:\users\user\miniconda3\lib\site-packages\spleeter\utils\estimator.py", line 71, in to_predictor
    return predictor.from_saved_model(latest)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\contrib\predictor\predictor_factories.py", line 153, in from_saved_model
    config=config)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\contrib\predictor\saved_model_predictor.py", line 153, in __init__
    loader.load(self._session, tags.split(','), export_dir)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 422, in load
    **saver_kwargs)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1473, in _import_meta_graph_with_return_elements
    **kwargs))
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 857, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 443, in import_graph_def
    _ProcessNewOps(graph)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 236, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3751, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3751, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3641, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "c:\users\user\miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 |
| Installation type | Conda |
| RAM available     | 32 GB |
| Hardware spec     | Ryzen 9 3900x / RTX 2070 Super |

**Comment by aidv** [comment]
I think you need CUDA 10.1

**Comment by SamusAranX** [comment]
I uninstalled CUDA 10.2 and replaced it with 10.1. Then I reinstalled spleeter with `conda remove spleeter-gpu && conda install -c conda-forge spleeter-gpu` to be sure. It's still failing with the same error message.

**Comment by aidv** [comment]
Try adding `python -m` before `spleeter separate ...` so it looks something like `python -m spleeter separate ...`

**Comment by SamusAranX** [comment]
That doesn't make a difference. `spleeter` alone already correctly executes the tool.

**Comment by aidv** [comment]
How long is the audio file? You might need to chop it into smaller pieces and then run it through spleeter.

**Comment by SamusAranX** [comment]
That is not the problem. The problem I have is laid out in the initial post.

**Comment by mmoussallam** [comment]
Hi @SamusAranX 

Is it only for your audio file or do you also have the same issue with the example one ?

**Comment by SamusAranX** [comment]
Spleeter does not start for *any* audio file.

**Comment by mmoussallam** [comment]
Hi @SamusAranX 

We are unfortunately not able to reproduce this, mainly because we have no machine with gpu cards running windows. 

It is defintely an issue with your tensorflow install though, as described for instance [here](https://github.com/tensorflow/tensorflow/issues/24828). I would suggest you to reinstall the tensorflow-gpu package and test some tutorial code prior to trying spleeter.

**Comment by trigdev** [comment]
> Spleeter does not start for _any_ audio file.

Did you get this working? I can run spleeter-gpu but it is lower than CPU processing? I am using CUDA 10.2 GTX970

**Comment by JISSJOHNSON** [comment]
i am also facing the same issue with gpu version.

**Comment by aidv** [comment]
Here are some possible fixes:

1. Check CUDA version. You should install 10.1
2. Check FFMPEG installation
3. Try running spleeter with `python -m spleeter.......`
4. Split audio files into several pieces if the whole audio file fails

**Comment by JISSJOHNSON** [comment]
the only way to work is fragmenting the song with a duration of 90sec for 2stems and 45sec fragment for 5stems. is there any way to increase the resource allocation of tenserflow ??

**Comment by Faylixe** [comment]
Well I think the real problem here is that you are maybe trying to use the GPU version with an AMD GPU. Cuda is a proprietary Nvidia solution and even if there is existing bridge for AMD hardware (such as [ROCm](https://rocm.github.io)), I think the currently used TensorFlow version does not support such configuration.

**Comment by SamusAranX** [comment]
When I opened this issue, I was using a GTX 1070. I have an RTX 2070 Super now and it's still not working.

**Comment by Laurent172** [comment]
Try this:
- Install Python 3.7 and install Anaconda first (but I guess you all ready did)
- Following commands in Anaconda prompt:
- **conda update --all** (Always better to be up-to-date)
- **conda create --name tfgpu tensorflow-gpu** (creates an environment with everything working fine. It takes only one command line, it's amazing (source: https://towardsdatascience.com/tensorflow-gpu-installation-made-easy-use-conda-instead-of-pip-52e5249374bc))
- **conda activate tfgpu** (enter environment)
- **conda install -c conda-forge spleeter-gpu** (install spleeter for GPU, normally it will downgrade Tensorflow from 2.0 (or 2.1 I don't remember precisely) to 1.14 but it's ok)

Enjoy (if it's working) :)

**Comment by aidv** [comment]
@Laurent172 a few questions:

- What CUDA version do you have installed?
- Are you using the command line or the api of spleeter?

**Comment by Laurent172** [comment]
You don't need to install CUDA if I remember well, The technique I mentionned does it for you. 
I used the command line.

**Comment by aidv** [comment]
@Laurent172 really? Nice. But I can't get it to work. Is it for the latest Spleeter or the old one with the label `cf202003`?

I am having so much issues it's insane.
