### ISSUE TITLE
[Bug] Invalid device ordinal value while setting up XLA_GPU_JIT with spleeter-gpu

### ISSUE THREAD

**Issue by DavidDoukhan** [deezer/spleeter#26]
## Description

While trying to use spleeter gpu implementation installed with conda, I faced execution exceptions.

## Step to reproduce

1. Installed using
```
git clone https://github.com/Deezer/spleeter
conda env create -f spleeter/conda/spleeter-gpu.yaml
conda activate spleeter-gpu
(spleeter-gpu) ddoukhan@lucrate-titan:/tmp$ conda --version
conda 4.6.14
(spleeter-gpu) ddoukhan@lucrate-titan:/tmp$ python --version
Python 3.7.3
```

2. Run as 
```
(spleeter-gpu) ddoukhan@lucrate-titan:/tmp$ mkdir output
(spleeter-gpu) ddoukhan@lucrate-titan:/tmp$ file mytest.wav 
mytest.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz
(spleeter-gpu) ddoukhan@lucrate-titan:/tmp$ spleeter separate -i mytest.wav -p spleeter:2stems -o output

```
3. Got 
```
INFO:tensorflow:Using config: {'_model_dir': 'pretrained_models/2stems', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.7
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f3c8857d2e8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/spleeter/model/functions/unet.py:29: The name tf.keras.initializers.he_uniform is deprecated. Please use tf.compat.v1.keras.initializers.he_uniform instead.

INFO:tensorflow:Apply unet for vocals_spectrogram
INFO:tensorflow:Apply unet for accompaniment_spectrogram
INFO:tensorflow:Done calling model_fn.
WARNING:tensorflow:From /home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
Traceback (most recent call last):
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/spleeter/__main__.py", line 48, in entrypoint
    main(sys.argv)
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/spleeter/__main__.py", line 42, in main
    entrypoint(arguments, params)
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/spleeter/commands/separate.py", line 180, in entrypoint
    output_naming=output_naming)
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/spleeter/commands/separate.py", line 133, in process_audio
    for sample in prediction:
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 635, in predict
    hooks=all_hooks) as mon_sess:
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1007, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1200, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1205, in _create_session
    return self._sess_creator.create_session()
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 871, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 647, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/training/session_manager.py", line 290, in prepare_session
    config=config)
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/training/session_manager.py", line 194, in _restore_checkpoint
    sess = session.Session(self._target, graph=self._graph, config=config)
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1570, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/ddoukhan/miniconda3/envs/spleeter-gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 693, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid device ordinal value (1). Valid range is [0, 0].
	while setting up XLA_GPU_JIT device number 1

```

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Ubuntu 16.04 |
| Installation type | Conda              |
| RAM available     | 64 Go                             |
| Hardware spec     | GeForce GTX TITAN X (maxwell architecture)             |

## Additional context

The GPU that can be used to do the computations is inserted on slot 1. Slot 0 cannot be used with tensorflow.

```
(spleeter-gpu) ddoukhan@lucrate-titan:/tmp$ nvidia-smi -L
GPU 0: GeForce GT 710 (UUID: GPU-17ab4408-c72f-4119-5394-484ff445c66c)
GPU 1: GeForce GTX TITAN X (UUID: GPU-3228b331-6dc2-3944-1c04-15fde2ff42a1)
```

**Comment by mmoussallam** [comment]
Hi David! 

Seems like a tensorflow related issue where the device numbering is messed up. Unfortunately I don't think we can reproduce it easily..

**Comment by DavidDoukhan** [comment]
Hi Manuel,

Meanwhile I found a small workaround allowing to make it run properly. This requires to set the CUDA_VISIBLE_DEVICES environment variable:
`CUDA_VISIBLE_DEVICES=1 spleeter separate -i mytest.wav -p spleeter:2stems -o output`

By the way, thanks a lot for this open-source contribution!

Kind regards,

**Comment by Faylixe** [comment]
> Hi Manuel,
> 
> Meanwhile I found a small workaround allowing to make it run properly. This requires to set the CUDA_VISIBLE_DEVICES environment variable:
> `CUDA_VISIBLE_DEVICES=1 spleeter separate -i mytest.wav -p spleeter:2stems -o output`
> 
> By the way, thanks a lot for this open-source contribution!
> 
> Kind regards,

Thanks for the workaround, we will add this information to the FAQ available in the wiki :)

**Comment by mmoussallam** [comment]
I've added it to the wiki. Closing the issue. Thanks David!
