### ISSUE TITLE
[Bug] Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by mmxxdungeon** [deezer/spleeter#273]
## Step to reproduce

1. Put the seperate command
2. Pressed enter
3. Got `Failed to load the native TensorFlow` error

## Output

PS C:\Users\Purple Flippy\Music> spleeter separate -i 'song.wav' -p spleeter:4stems -o splits
Traceback (most recent call last):
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Purple Flippy\AppData\Local\Programs\Python\Python37\Scripts\spleeter.exe\__main__.py", line 9, in <module>
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\purple flippy\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 |
| Installation type | Powershell             |
| RAM available     | 16GB                             |
| Hardware spec     | GPU / CPU / etc ...             |

**Comment by lamhaoyin2** [comment]
It seems that your CPU does not support AVX. You can try to build tensorflow from source on your machine and manually install your compiled package. It works for me.

**Comment by mmxxdungeon** [comment]
> It seems that your CPU does not support AVX. You can try to build tensorflow from source on your machine and manually install your compiled package. It works for me.

How do you do that?

**Comment by lamhaoyin2** [comment]
> > It seems that your CPU does not support AVX. You can try to build tensorflow from source on your machine and manually install your compiled package. It works for me.
> 
> How do you do that?

Follow the steps described in https://www.tensorflow.org/install/source_windows . For spleeter, you have to manually download the source code of tensorflow version 1.14.0 instead of downloading them by git (it will download a newer version which is not 1.14.0)

**Comment by mmxxdungeon** [comment]
> > > It seems that your CPU does not support AVX. You can try to build tensorflow from source on your machine and manually install your compiled package. It works for me.
> > 
> > 
> > How do you do that?
> 
> Follow the steps described in https://www.tensorflow.org/install/source_windows . For spleeter, you have to manually download the source code of tensorflow version 1.14.0 instead of downloading them by git (it will download a newer version which is not 1.14.0)

Already followed the steps then stopped at the "Download the TensorFlow source code" section. How do I manually install it without by git, I try to find a way but i dont see it?

**Comment by lamhaoyin2** [comment]
> > > > It seems that your CPU does not support AVX. You can try to build tensorflow from source on your machine and manually install your compiled package. It works for me.
> > > 
> > > 
> > > How do you do that?
> > 
> > 
> > Follow the steps described in https://www.tensorflow.org/install/source_windows . For spleeter, you have to manually download the source code of tensorflow version 1.14.0 instead of downloading them by git (it will download a newer version which is not 1.14.0)
> 
> Already followed the steps then stopped at the "Download the TensorFlow source code" section. How do I manually install it without by git, I try to find a way but i dont see it?

You can find the code on https://github.com/tensorflow/tensorflow/releases/tag/v1.14.0 .
Download it, uncompress it, and simply skip the "Download the TensorFlow source code" section.
