### ISSUE TITLE
[Bug] Crash when running spleeter in parallel

### ISSUE THREAD

**Issue by DanielAsher** [deezer/spleeter#280]
## Description

When running spleeter twice simultaneously from the console, I often get one instance crashing.

## Step to reproduce

1. Installed using `pip3 install spleeter`

2. Run as 
Terminal 1:
`spleeter separate --verbose -i ./output/audio/wN9bXy_fiOE.mp3 -p spleeter:4stems -c mp3 -o ./output/audio/`
Terminal 2:
`spleeter separate --verbose -i ./output/audio/hiu9WSl4OKg.mp3 -p spleeter:4stems -c mp3 -o ./output/audio/`

3. Got `tensorflow.python.framework.errors_impl.NotFoundError: /var/folders/yk/9r3nhhws2pvc191dbh7885rh0000gn/T/serving/temp-b'1582632034'/saved_model.pb; No such file or directory`

## Output
Terminal 1:
```bash
spleeter separate --verbose -i ./output/audio/wN9bXy_fiOE.mp3 -p spleeter:4stems -c mp3 -o ./output/audio/
INFO:tensorflow:Using config: {'_model_dir': 'pretrained_models/4stems', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.7
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x13744ec10>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/spleeter/model/functions/unet.py:30: The name tf.keras.initializers.he_uniform is deprecated. Please use tf.compat.v1.keras.initializers.he_uniform instead.

INFO:tensorflow:Apply unet for vocals_spectrogram
INFO:tensorflow:Apply unet for drums_spectrogram
INFO:tensorflow:Apply unet for bass_spectrogram
INFO:tensorflow:Apply unet for other_spectrogram
INFO:tensorflow:Done calling model_fn.
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
INFO:tensorflow:Signatures INCLUDED in export for Classify: None
INFO:tensorflow:Signatures INCLUDED in export for Regress: None
INFO:tensorflow:Signatures INCLUDED in export for Predict: ['serving_default']
INFO:tensorflow:Signatures INCLUDED in export for Train: None
INFO:tensorflow:Signatures INCLUDED in export for Eval: None
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from pretrained_models/4stems/model
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
Traceback (most recent call last):
  File "/usr/local/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/usr/local/lib/python3.7/site-packages/spleeter/commands/separate.py", line 43, in entrypoint
    synchronous=False
  File "/usr/local/lib/python3.7/site-packages/spleeter/separator.py", line 123, in separate_to_file
    sources = self.separate(waveform)
  File "/usr/local/lib/python3.7/site-packages/spleeter/separator.py", line 86, in separate
    predictor = self._get_predictor()
  File "/usr/local/lib/python3.7/site-packages/spleeter/separator.py", line 58, in _get_predictor
    self._predictor = to_predictor(estimator)
  File "/usr/local/lib/python3.7/site-packages/spleeter/utils/estimator.py", line 66, in to_predictor
    estimator.export_saved_model(directory, receiver)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 732, in export_saved_model
    strip_default_attrs=True)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 863, in _export_all_saved_models
    builder.save(as_text)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/builder_impl.py", line 420, in save
    file_io.write_string_to_file(path, self._saved_model.SerializeToString())
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 347, in write_string_to_file
    f.write(file_content)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 106, in write
    self._prewrite_check()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 92, in _prewrite_check
    compat.as_bytes(self.__name), compat.as_bytes(self.__mode))
tensorflow.python.framework.errors_impl.NotFoundError: /var/folders/yk/9r3nhhws2pvc191dbh7885rh0000gn/T/serving/temp-b'1582632034'/saved_model.pb; No such file or directory
```

Terminal 2:

```
spleeter separate --verbose -i ./output/audio/hiu9WSl4OKg.mp3 -p spleeter:4stems -c mp3 -o ./output/audio/
INFO:tensorflow:Using config: {'_model_dir': 'pretrained_models/4stems', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.7
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x130549790>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/spleeter/model/functions/unet.py:30: The name tf.keras.initializers.he_uniform is deprecated. Please use tf.compat.v1.keras.initializers.he_uniform instead.

INFO:tensorflow:Apply unet for vocals_spectrogram
INFO:tensorflow:Apply unet for drums_spectrogram
INFO:tensorflow:Apply unet for bass_spectrogram
INFO:tensorflow:Apply unet for other_spectrogram
INFO:tensorflow:Done calling model_fn.
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
INFO:tensorflow:Signatures INCLUDED in export for Classify: None
INFO:tensorflow:Signatures INCLUDED in export for Regress: None
INFO:tensorflow:Signatures INCLUDED in export for Predict: ['serving_default']
INFO:tensorflow:Signatures INCLUDED in export for Train: None
INFO:tensorflow:Signatures INCLUDED in export for Eval: None
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from pretrained_models/4stems/model
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: /var/folders/yk/9r3nhhws2pvc191dbh7885rh0000gn/T/serving/temp-b'1582632034'/saved_model.pb
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow/contrib/predictor/saved_model_predictor.py:153: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
INFO:tensorflow:Restoring parameters from /var/folders/yk/9r3nhhws2pvc191dbh7885rh0000gn/T/serving/1582632034/variables/variables
DEBUG:spleeter:Writing file ./output/audio/hiu9WSl4OKg/vocals.mp3
DEBUG:spleeter:Writing file ./output/audio/hiu9WSl4OKg/bass.mp3
DEBUG:spleeter:Writing file ./output/audio/hiu9WSl4OKg/other.mp3
DEBUG:spleeter:Writing file ./output/audio/hiu9WSl4OKg/drums.mp3
INFO:spleeter:File ./output/audio/hiu9WSl4OKg/bass.mp3 written
INFO:spleeter:File ./output/audio/hiu9WSl4OKg/vocals.mp3 written
INFO:spleeter:File ./output/audio/hiu9WSl4OKg/other.mp3 written
INFO:spleeter:File ./output/audio/hiu9WSl4OKg/drums.mp3 written
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS  |
| Installation type | pip        |
| RAM available     | 16GB                             |
| Hardware spec     | 2.9 GHz Quad-Core Intel Core i7     |

## Additional context

This seems to be a simple race condition on the temp folder name `1582632034` which both instances fight over.

**Comment by mmoussallam** [comment]
Hi @DanielAsher ,

Indeed, it seems both process want to access the file at the same time and one of them crashes. 

Be aware that spleeter already run computations in parallel, so you would probably not benefit much from running two instances at the same time anyway. It's probably best to just compute your files in a sequential manner using the [batch processing feature](https://github.com/deezer/spleeter/wiki/2.-Getting-started#batch-processing). 

Hope this helps
