### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by benny-writus** [deezer/spleeter#285]
C:\Users\amy\Desktop\vaan>python3 -m spleeter separate -i C:\Users\amy\Desktop\vaan\vaan.mp3 -p spleeter:4stems -o "e:\output"
Traceback (most recent call last):
  File "C:\Python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python3\lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Python3\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Python3\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Python3\lib\site-packages\spleeter\commands\separate.py", line 43, in entrypoint
    synchronous=False
  File "C:\Python3\lib\site-packages\spleeter\separator.py", line 122, in separate_to_file
    sample_rate=self._sample_rate)
  File "C:\Python3\lib\site-packages\spleeter\audio\ffmpeg.py", line 63, in load
    probe = ffmpeg.probe(path)
  File "C:\Python3\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python3\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Python3\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Kindly help me with the error.

**Comment by mmoussallam** [comment]
Hi @benny-writus  take a look at https://github.com/deezer/spleeter/wiki/5.-FAQ#ffprobe-errors
