### ISSUE TITLE
Only errors since I updated

### ISSUE THREAD

**Issue by Lemm99** [deezer/spleeter#296]
I did a git pull origin master and a conda update --all and now I'm getting all sorts of problems I never had before. What changed and how do I go back to a working version??

spleeter separate -i "music.flac" -p spleeter:2stems-16kHz -o output
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/user/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[47,32,256,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node concatenate_4/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[strided_slice_23/_309]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[47,32,256,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node concatenate_4/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda3/bin/spleeter", line 10, in <module>
    sys.exit(entrypoint())
  File "/home/user/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/home/user/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/home/user/miniconda3/lib/python3.7/site-packages/spleeter/commands/separate.py", line 43, in entrypoint
    synchronous=False
  File "/home/user/miniconda3/lib/python3.7/site-packages/spleeter/separator.py", line 123, in separate_to_file
    sources = self.separate(waveform)
  File "/home/user/miniconda3/lib/python3.7/site-packages/spleeter/separator.py", line 89, in separate
    'audio_id': ''})
  File "/home/user/miniconda3/lib/python3.7/site-packages/tensorflow/contrib/predictor/predictor.py", line 77, in __call__
    return self._session.run(fetches=self.fetch_tensors, feed_dict=feed_dict)
  File "/home/user/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/user/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/user/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[47,32,256,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node concatenate_4/concat (defined at /lib/python3.7/site-packages/spleeter/utils/estimator.py:71) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[strided_slice_23/_309]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[47,32,256,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node concatenate_4/concat (defined at /lib/python3.7/site-packages/spleeter/utils/estimator.py:71) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Original stack trace for 'concatenate_4/concat':
  File "/bin/spleeter", line 10, in <module>
    sys.exit(entrypoint())
  File "/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/lib/python3.7/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/lib/python3.7/site-packages/spleeter/commands/separate.py", line 43, in entrypoint
    synchronous=False
  File "/lib/python3.7/site-packages/spleeter/separator.py", line 123, in separate_to_file
    sources = self.separate(waveform)
  File "/lib/python3.7/site-packages/spleeter/separator.py", line 86, in separate
    predictor = self._get_predictor()
  File "/lib/python3.7/site-packages/spleeter/separator.py", line 58, in _get_predictor
    self._predictor = to_predictor(estimator)
  File "/lib/python3.7/site-packages/spleeter/utils/estimator.py", line 71, in to_predictor
    return predictor.from_saved_model(latest)
  File "/lib/python3.7/site-packages/tensorflow/contrib/predictor/predictor_factories.py", line 153, in from_saved_model
    config=config)
  File "/lib/python3.7/site-packages/tensorflow/contrib/predictor/saved_model_predictor.py", line 153, in __init__
    loader.load(self._session, tags.split(','), export_dir)
  File "/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1473, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/lib/python3.7/site-packages/tensorflow/python/framework/meta_graph.py", line 857, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 443, in import_graph_def
    _ProcessNewOps(graph)
  File "/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 236, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3751, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3751, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3641, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by alreadytaikeune** [comment]
Hi @Lemm99 , are you sure no other process are currently using your GPU and taking the memory?

You can try the code in the following PR https://github.com/deezer/spleeter/pull/282#issuecomment-599962300 
Choosing librosa as stft backend will reduce the memory usage and might help with your problem.

**Comment by Lemm99** [comment]
NVIDIA X Server Settings
Graphics Processor: GeForce GTX 1080
Total Memory: 8192 MB
Total Dedicated Memory: 8116 MB
Used Dedicated Memory: 284 MB (3%)
GPU Utilization: 0 %
Video Engine Utilization: 0 %
PCIe Generation: Gen3
Maximum PCIe Link Width: x16
Maximum PCIe Link Speed: 8.0 GT/s
PCIe Bandwidth Utilization: 0 %
That's idle. 

When I run the spleeter command on a 9 minute FLAC the Dedicated Memory peaks at 6339 MB (78%) and GPU spikes to 100% for 1 second. I'll try your code soon but this never happened before I updated conda and spleeter yesterday.

**Comment by Lemm99** [comment]
I pulled your code. The tensorflow backend for stfts results in the same error as my first report. The librosa backend for stfts locks my computer up. I use linux mint 19.3 btw.

**Comment by Lemm99** [comment]
This happens because the latest tensorflow requires CUDA 10 or higher. Linux Mint 19.3 is stuck on CUDA 9. Spleeter works by forcing CPU (-B librosa).

**Comment by alreadytaikeune** [comment]
Hi @Lemm99 you are right. We have noticed this issue and are in the process of re-building newer images with CUDA 10.
