### ISSUE TITLE
Unable to convert into 4 stems and 5 stems after the failure in downloading the libraries for the first time

### ISSUE THREAD

**Issue by imkikus** [deezer/spleeter#299]
I tried converting an audio file into 4 stems and 5 stems for the first time. 2 stems works fine. The problem is while I was trying to convert into 4 stems and 5 stems for the first time. My internet dropped down and was unable to download the required libraries of the same. After that while I try to use 4 stems/5 stems as an option it throws me this error. I see that the pretrained models failed due to the absence of the required librarires(4 stems and 5 stems). Could you please help me with the steps to reinstall the 4 stems and 5 stems libraries and unblock me? Thanks.

Seems like [this issue](https://github.com/deezer/spleeter/issues/189) is reported earlier. Which FAQ you meant @mmoussallam ? Can you please share the link?
I couldn't find the solution :(

kikus@kikus:~$ spleeter separate -i Yelu\ Bannada.mp3 -p spleeter:4stems -o output
Traceback (most recent call last):
  File "/home/kikus/anaconda3/bin/spleeter", line 10, in <module>
    sys.exit(entrypoint())
  File "/home/kikus/anaconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/home/kikus/anaconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/home/kikus/anaconda3/lib/python3.7/site-packages/spleeter/commands/separate.py", line 43, in entrypoint
    synchronous=False
  File "/home/kikus/anaconda3/lib/python3.7/site-packages/spleeter/separator.py", line 123, in separate_to_file
    sources = self.separate(waveform)
  File "/home/kikus/anaconda3/lib/python3.7/site-packages/spleeter/separator.py", line 86, in separate
    predictor = self._get_predictor()
  File "/home/kikus/anaconda3/lib/python3.7/site-packages/spleeter/separator.py", line 58, in _get_predictor
    self._predictor = to_predictor(estimator)
  File "/home/kikus/anaconda3/lib/python3.7/site-packages/spleeter/utils/estimator.py", line 66, in to_predictor
    estimator.export_saved_model(directory, receiver)
  File "/home/kikus/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 732, in export_saved_model
    strip_default_attrs=True)
  File "/home/kikus/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 827, in _export_all_saved_models
    self._model_dir))
ValueError: Couldn't find trained model at pretrained_models/4stems.

**Comment by mmoussallam** [comment]
Hi @imkikus , you'll need to clean the \\pretrained_models` directory this will force a re-download of the models. Check the FAQ for more details.
