### ISSUE TITLE
ValueError: Can't load save_path when it is None

### ISSUE THREAD

**Issue by patcheszone** [deezer/spleeter#306]
## Description

After resetting my computer, I can no longer successfully run Spleeter. 

## Step to reproduce

1. Installed using Conda
2. Run $ spleeter separate -i /Users/user/Desktop/song.mp3 -p spleeter:2stems -o output
2. Got `ValueError: Can't load save_path when it is None.`

## Output

Traceback (most recent call last):
  File "/opt/miniconda3/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/opt/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/opt/miniconda3/lib/python3.7/site-packages/spleeter/commands/separate.py", line 45, in entrypoint
    synchronous=False
  File "/opt/miniconda3/lib/python3.7/site-packages/spleeter/separator.py", line 191, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "/opt/miniconda3/lib/python3.7/site-packages/spleeter/separator.py", line 157, in separate
    return self.separate_librosa(waveform, audio_descriptor)
  File "/opt/miniconda3/lib/python3.7/site-packages/spleeter/separator.py", line 147, in separate_librosa
    saver.restore(sess, latest_checkpoint)
  File "/opt/miniconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1274, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

## Environment
|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS - Mojave |
| Installation type | Conda       |
| RAM available     | 16 GB 2133 MHz LPDDR3            |
| Hardware spec     | 2.8 GHz Intel Core i7        |

## Additional context

I had no issues previously, and can't account for what may be happening here. Help is very much appreciated!

**Comment by Cathon** [comment]
I have the same problem.

OS; Windows 10
Installation type: Conda

**Comment by caioburin** [comment]
Me too, same problem. It was working before.

**Comment by patcheszone** [comment]
Still no help offered on this? Seems to be an issue many of us are having

**Comment by Cathon** [comment]
> 
> 
> I have the same problem.
> 
> OS; Windows 10
> Installation type: Conda

Finally, I used docker image to run spleeter successfully.

**Comment by Juan-Carlos-Rodero-Sales-Bose** [comment]
Facing same issue when installed through conda

**Comment by ad34** [comment]
any workaround, looks like a corrupted save file from tensorflow

**Comment by Chaojidahoufeng** [comment]
same problem...

**Comment by Abukamel** [comment]
same here

**Comment by ahkimkoo** [comment]
我也遇到了python3.7， 3.8

**Comment by kevin1078** [comment]
The error is caused by the lack of the pretrained data model. 

Here is the solution: git clone spleeter to local directory, say ~/spleeter, then cd spleeter, then run the spleeter command; this time spleeter won't throw an exception, but download the pretrained data model needed for execution.

**Comment by Christilut** [comment]
Same problem here sporadically.

```
spleeter separate -i "/Users/user/Music/Genre/80's Music/Ain't No Stopping Us Now - McFadden & Whitehead.mp3" -p spleeter:2stems-16kHz -o "/var/folders/ll/_n09zd5j62q2gbyhc74456m80000gn/T/vocalsplitter/results"
Traceback (most recent call last):
  File "/Users/user/opt/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/user/opt/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/user/opt/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 58, in <module>
    entrypoint()
  File "/Users/user/opt/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/Users/user/opt/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/Users/user/opt/miniconda3/lib/python3.7/site-packages/spleeter/commands/separate.py", line 45, in entrypoint
    synchronous=False
  File "/Users/user/opt/miniconda3/lib/python3.7/site-packages/spleeter/separator.py", line 217, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "/Users/user/opt/miniconda3/lib/python3.7/site-packages/spleeter/separator.py", line 184, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "/Users/user/opt/miniconda3/lib/python3.7/site-packages/spleeter/separator.py", line 169, in _separate_librosa
    saver.restore(sess, latest_checkpoint)
  File "/Users/user/opt/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
```

**Comment by kariuki-alan** [comment]
I have also encountered the same issue.

**Comment by mmoussallam** [comment]
Hi all,

I've updated the FAQ with an entry on [this](https://github.com/deezer/spleeter/wiki/5.-FAQ#save-path-error). Hope this helps.

**Comment by caioburin** [comment]
That did not work for me, @mmoussallam . It keeps throwing a AttributeError: __enter__ error.
What I did instead, which seemed to work, was to download the model directly from github (https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz) and extract them into the pretrained_mode/2stems folder. Doing that, it works

**Comment by asa-charles-ho** [comment]
> That did not work for me, @mmoussallam . It keeps throwing a AttributeError: **enter** error.
> What I did instead, which seemed to work, was to download the model directly from github (https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz) and extract them into the pretrained_mode/2stems folder. Doing that, it works

After that, it should be uncompress in the folder.

**Comment by tareqdayya** [comment]
The manual download of the stems did not do it for me. I, too, moved them into the pretrained_models directory which the executable was going to throw them anyway. I also uncompressed the tar file in the directory.
Still getting the same error in the original post.

**Comment by An0nDev** [comment]
If you Ctrl+C while spleeter is downloading a pretrained model, you may end up with this error, at which point you can simply delete the `pretrained_models` directory in your current directory and re-run spleeter to redownload the pretrained model.

**Comment by trumandaniels** [comment]
> The error is caused by the lack of the pretrained data model.
> 
> Here is the solution: git clone spleeter to local directory, say ~/spleeter, then cd spleeter, then run the spleeter command; this time spleeter won't throw an exception, but download the pretrained data model needed for execution.

git clone https://github.com/Deezer/spleeter && cd spleeter

**Comment by happyTonakai** [comment]
Problem solved.
Download pretrained models from release, and then unzip&put it in spleeter\pretrained_models\2stems

**Comment by pxvp2008** [comment]
> 我也遇到了python3.7， 3.8

[(https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz)](https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz)，去上面下载预制模型，然后放在你执行spleeter时的当前目录下，然后你神奇的发现可以了！
