### ISSUE TITLE
Training Error | FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by avantguard** [deezer/spleeter#313]
Any help would be highly appreciated with the error below:

```
INFO:spleeter:Start model training
Traceback (most recent call last):
  File "/usr/local/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.6/dist-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/commands/train.py", line 98, in entrypoint
    evaluation_spec)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1025, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1116, in _call_input_fn
    return input_fn(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/dataset.py", line 78, in get_training_dataset
    wait_for_cache=False)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/dataset.py", line 406, in build
    dataset = self.cache(dataset, cache_directory, wait_for_cache)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/dataset.py", line 367, in cache
    os.makedirs(cache_path, exist_ok=True)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by mmoussallam** [comment]
Hi @avantguard 

Please use the full Issue template, with details on your install and the exact command you're launching. It'll help us know how to help you.
