### ISSUE TITLE
[Bug] pip installation no longer working

### ISSUE THREAD

**Issue by gdesmott** [deezer/spleeter#327]
## Description

Looks like it's no longer possible to install Spleeter using `pip`. Package should be fixed or [documentation](https://github.com/deezer/spleeter/wiki/1.-Installation#using-pip) updated.

## Step to reproduce

`pip install spleeter`

## Output

```bash
ERROR: Could not find a version that satisfies the requirement spleeter (from versions: none)
ERROR: No matching distribution found for spleeter
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Linux |
| Installation type | pip             |
| RAM available     | 8Go                             |
| Hardware spec     | CPU             |

**Comment by mmoussallam** [comment]
Hi @gdesmott 

indeed there seems to be a broken dependency on the tensorflow side. We'll fix that very soon. In the meantime `pip install spleeter==1.4.9` is working.

**Comment by gdesmott** [comment]
Actually it looks like it requires `python <3.8` while I have `3.8.2`

```bash
$ pip install spleeter -v
Created temporary directory: /tmp/pip-ephem-wheel-cache-xwl5qy3y
Created temporary directory: /tmp/pip-req-tracker-u0rhyiyt
Created requirements tracker '/tmp/pip-req-tracker-u0rhyiyt'
Created temporary directory: /tmp/pip-install-1qgzsma3
1 location(s) to search for versions of spleeter:
* https://pypi.org/simple/spleeter/
Getting page https://pypi.org/simple/spleeter/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/spleeter/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/spleeter/ HTTP/1.1" 304 0
Analyzing links from page https://pypi.org/simple/spleeter/
  Link requires a different Python (3.8.2 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/67/81/7234f9f5f61b5ec50c346e8bf5a2313008f0ea655a640bbc345a200e3fdb/spleeter-1.4.1.tar.gz#sha256=d0c1013a0ce69f8c12d103632f9c91362c6c31cba8a7f91e709fa28c5172ec8d (from https://pypi.org/simple/spleeter/) (requires-python:>=3.6, <3.8)
  Link requires a different Python (3.8.2 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/d0/8d/3951d180a89ea4d860d3a36bb505b22a2737a3bd28400ab51c901b070d99/spleeter-1.4.3.tar.gz#sha256=1842388ea9edd938f91f75bbbc33d40d56c21492c30b2dc8e2664faeff97bd46 (from https://pypi.org/simple/spleeter/) (requires-python:>=3.6, <3.8)
  Link requires a different Python (3.8.2 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/56/ea/e3739d9f2ed1d21d9c5c904b493032366a1a1092810aa8accd3d20e64ef2/spleeter-1.4.4.tar.gz#sha256=148cb583000c0f45e8905dd7073dd86d4cdd9dd8f54a145c8ce97d6658033c42 (from https://pypi.org/simple/spleeter/) (requires-python:>=3.6, <3.8)
  Link requires a different Python (3.8.2 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/22/f2/91af3c0055c70fb75d4f5e59be813d706e79d09afc9e1ce439202d7849e4/spleeter-1.4.5.tar.gz#sha256=4eeae3ae16649f5d400c632a0085d8e8f61ba5057bf27401f1f9adaa28cb39a5 (from https://pypi.org/simple/spleeter/) (requires-python:>=3.6, <3.8)
  Link requires a different Python (3.8.2 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/81/63/ef200da95dd61cfdc2afbe33f57d17280da15c0b94b985626a87d0d92333/spleeter-1.4.6.tar.gz#sha256=8a37c94124df7d0c228ab51552630455f9810587fbf895af93977c47687189fe (from https://pypi.org/simple/spleeter/) (requires-python:>=3.6, <3.8)
  Link requires a different Python (3.8.2 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/ae/b2/ff31ceba8b57a9259cbc15b95a31d69b9599b8221dded6b7cb28255b289c/spleeter-1.4.7.tar.gz#sha256=3f7bcae385e3a6dbf38502684edb0fa0ea5c3f1af27720ab5d76543e0cae235b (from https://pypi.org/simple/spleeter/) (requires-python:>=3.6, <3.8)
  Link requires a different Python (3.8.2 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/3c/35/ce2d7a12fd927a53f87bbcae22966de0d2ad3710398dd4349528bff41fe3/spleeter-1.4.8.tar.gz#sha256=25f3d830729f0691300e70d02d56ea0d767b8fcbfd6bc1cee5054c2d0eea9801 (from https://pypi.org/simple/spleeter/) (requires-python:>=3.6, <3.8)
  Link requires a different Python (3.8.2 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/d0/d7/82c00e25289d689ac33c69089d88524b5044042d106918b819197d166156/spleeter-1.4.9.tar.gz#sha256=83a8e287aacf56e99e6443c6f4f5d333a229e9edc8a0b5c0d8fbf1f164e7dbb0 (from https://pypi.org/simple/spleeter/) (requires-python:>=3.6, <3.8)
  Link requires a different Python (3.8.2 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/a3/06/b9ac56a391aee8f40473fe0c81225a379d76b989762c876ba585cdf27a86/spleeter-1.5.0.tar.gz#sha256=c98331ce1e9db5cd686a5c4856c196654291ea90447caa9676a3869f37934ed4 (from https://pypi.org/simple/spleeter/) (requires-python:>=3.6, <3.8)
Given no hashes to check 0 links for project 'spleeter': discarding no candidates
ERROR: Could not find a version that satisfies the requirement spleeter (from versions: none)
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-u0rhyiyt'
ERROR: No matching distribution found for spleeter
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 401, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 202, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 368, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 314, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, self.require_hashes)
  File "/usr/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 226, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3.8/site-packages/pip/_internal/index.py", line 905, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for spleeter

$ python --version
Python 3.8.2
```

**Comment by Faylixe** [comment]
Yes, we do not support `3.8`. The PyPI package is only for 3.6 and 3.7. This is why is it not working. Please downgrade your Python version or use an isolated env instead with a specific python version.

**Comment by naticio** [comment]
I am trying to install in 3.7.3 and I'm getting the same error. any idea? or I am just tired?

```
Nat-Serrano (master) spleeter
$ pyenv global
3.7.3
Nat-Serrano (master) spleeter
$ pip install spleeter
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting spleeter
  ERROR: Could not find a version that satisfies the requirement spleeter (from versions: none)
ERROR: No matching distribution found for spleeter
Nat-Serrano (master) spleeter
$ 
```
