### ISSUE TITLE
[Bug] Using spleeter separate on Windows 10 fails, exception related to Numba core

### ISSUE THREAD

**Issue by kass-kass** [deezer/spleeter#347]
## Description

Installed Spleeter on Win 10 x64 with pip through latest Anaconda version - 2020.02. 

Running "spleeter separate" fails, throws exception saying DLL load failed, tracing to Numba error (tried with both python 3.7 and 3.6 environments).

## Step to reproduce

1. Install using pip install spleeter in Anaconda
2. Run any separate command
3. Error 

## Output

```
spleeter separate -i split.mp3 -o audio_output
Traceback (most recent call last):
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kassym\.conda\envs\snakes\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kassym\.conda\envs\snakes\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kassym\.conda\envs\snakes\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\spleeter\separator.py", line 23, in <module>
    from librosa.core import stft, istft
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\librosa\util\utils.py", line 10, in <module>
    import numba
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.misc.special import (
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "c:\users\kassym\.conda\envs\snakes\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: c:\users\kassym\.conda\envs\snakes\python.exe

```
## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 x64  |
| Installation type | pip |
| RAM available     | 16GB |
| Hardware spec     | Intel Core i7-8750H / GTX 1070 |

## Additional context

Standard steps taken on a clean machine - just downloaded and installed anaconda, there were no previous installations of python, anaconda, or spleeter.

**Comment by kass-kass** [comment]
I don't know why, but this bug report was auto-flagged as invalid right as I posted it. I filled in the form correctly as far as I can see, please let me know if there is missing information. This isn't an invalid report.

**Comment by desoconner** [comment]
i'm having exactly the same problem, followed this guys tutorial and can't work it out https://www.youtube.com/watch?v=tgnuOSLPwMI

**Comment by mmoussallam** [comment]
Hi @kass-kass 

This seems to be related to your anaconda install, in particular the `numba``package. Can you tell us what is the version of numba installed on your system ?

**Comment by yoomy3** [comment]
+1 on this. I am also on Windows 10 machine. I've been using Spleeter without error for now until I pulled the updates today.

First, it threw a ModuleNotFoundError of 'librosa'.
Once I manually installed librosa, now I am getting the exact same error. 

Below is the Numba version on my machine:
`Name: numba
Version: 0.49.0
Summary: compiling Python code using LLVM
Home-page: http://numba.github.com
Author: Anaconda, Inc.
Author-email: numba-users@continuum.io
License: BSD
Location: c:\programdata\miniconda3\lib\site-packages
Requires: llvmlite, setuptools, numpy
Required-by: resampy, librosa`

**Comment by mmoussallam** [comment]
Hi @kass-kass  @yoomy3  @desoconner 

This seem to be quite an odd behavior linked to some version of numba on windows: https://github.com/numba/numba/issues/4732 

I can only encourage you to manually force a `pip install numba==0.45.0`  as suggested as it seems to solve the issue (can't reproduce it myself)

**Comment by yoomy3** [comment]
Hi @mmoussallam 
Downgrading numba to 0.45.0 as you suggested temporarily fixed the issue. Thanks :)

**Comment by dankwartrustow** [comment]
This fixed the exact issue for me as well on Windows 10.
