### ISSUE TITLE
Help! I think I installed Spleeter wrong...

### ISSUE THREAD

**Issue by B34N5T3P** [deezer/spleeter#376]
Long story short, I think I screwed up my install. I started trying to do it manually installing FFmpeg and Python and using the pip command. I DL'ed 3.8 unknowingly that it would cause problems. Uninstalled Python and reinstalled 3.7.7, changed Path variable, etc. Successfully installed spleeter, but then started getting errors when trying to separate audio. So tried installing using Anaconda and got an unexpected error when using the conda command for installing spleeter. Not sure what to do next or where to even look. Help!

FWIW, here is the command and error that spits back out in my command prompt when attempting to split an audio file.

C:\WINDOWS\system32>spleeter separate -i F:\Music\Hip_Hop\03_Greedo_-_Netflix_&_Deal\03G-N&D[320]\03_Greedo_-_Netflix_&_Deal_[320]\02._Paid_In_Full.mp3 -o audio_output -p spleeter:4stems-16kHz
Traceback (most recent call last):
  File "C:\Users\B34N5\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.5.1', 'console_scripts', 'spleeter')()
  File "c:\users\b34n5\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\b34n5\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\b34n5\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "c:\users\b34n5\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 216, in separate_to_file
    sample_rate=self._sample_rate)
  File "c:\users\b34n5\appdata\local\programs\python\python37\lib\site-packages\spleeter\audio\ffmpeg.py", line 72, in load
    probe = ffmpeg.probe(path)
  File "c:\users\b34n5\appdata\local\programs\python\python37\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\users\b34n5\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\b34n5\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.

**Comment by mmoussallam** [comment]
Hi @B34N5T3P ,

Your system does not find the `ffprobe` command. There' probably something wrong wth your FFmpeg install, but I'm afraid we can't really help you with that. Try to have ffmpeg work (e.g. when the command `ffprobe<path_to_your_file>` have no more errors, you're all set!) first.
