### ISSUE TITLE
[Bug] Can't use custom trained model?

### ISSUE THREAD

**Issue by JavaShipped** [deezer/spleeter#390]
## Description
How do I use a model I have just trained? I have tried to declare the directory its in -p ~/modelDirectory.

Do I need to use spleeter validate first? Or have I missed a step? There isn't any documentation on how to actually use the model once its built.  

## Step to reproduce

1. Open PowerShell in my directory with my config, model and dataset and type `spleeter separate -i 'F:\SpleetTest\Validate\Mixture\S05E02 - A War on Two Fronts\fullmix.wav' -o F:\SpleetTest\Configs\output -p F:\SpleetTest\Configs\pretrained_models\filmModel'
2. Run.
3. Got `PermissionError: [Errno 13] Permission denied: 'F:\\SpleetTest\\Configs\\pretrained_models\\filmModel'` error

## Output

```
Traceback (most recent call last):
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\joe93\AppData\Local\Programs\Python\Python37\Scripts\spleeter.exe\__main__.py", line 9, in <module>
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 45, in main
    params = load_configuration(arguments.configuration)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\configuration.py", line 46, in load_configuration
    with open(descriptor, 'r') as stream:
PermissionError: [Errno 13] Permission denied: 'F:\\SpleetTest\\Configs\\pretrained_models\\filmModel'
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 (fully updated) |
| Installation type |  pip  |
| RAM available     | 16GB  |
| Hardware spec     | RTX2080 / Ryzen R2600 |

## Additional context

I have reinstalled python, spleeter and retrained the model. Every time getting the same error [errno 13].

**Comment by romi1502** [comment]
Hi @JavaShipped,
The `-p` option takes as input a json file that describes the parameters of the model. Have a look at [this one](https://github.com/deezer/spleeter/blob/master/configs/2stems/base_config.json) as an example.
You need to pass the same json file that you used for training your model to the `separate` command.

Note that the `model_dir` parameter in the json file indicates where the model checkpoint (where are the model weights) will be stored. If you use a relative path, be sure you run the `separate` command in the same directory as you ran the `train` one.

The `Permission denied` error that you get is a permission issue that should not be related to spleeter. Be sure to have proper permissions on the `model_dir` directory when you run the command.

**Comment by JavaShipped** [comment]
Okay, we have movement. I managed to run the seperate command, and it thought about it for a long time and powershell was eating up my CPU, so it was doing something.

But after about 30-40 seconds I got the error: ` ValueError: Cannot feed value of shape (25836, 2, 6) for Tensor 'mix_stft:0', which has shape '(?, 2049, 2)' `

I used the following spleeter imput command: spleeter separate -i 'F:\BluRay 5.1\Done\S01E01 - Ambush\fullmix.wav' -o output -p F:\SpleetTest\Configs\filmModel.json

And got the following full output

`Traceback (most recent call last):
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\joe93\AppData\Local\Programs\Python\Python37\Scripts\spleeter.exe\__main__.py", line 9, in <module>
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 228, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 195, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 181, in _separate_librosa
    outputs = sess.run(outputs, feed_dict=self._get_input_provider().get_feed_dict(features, stft, audio_id))
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1156, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (25836, 2, 6) for Tensor 'mix_stft:0', which has shape '(?, 2049, 2)' `

I'm not exactly sure what this means, as I've mentioned before I'm not familiar with tensor or python (as you might be able to see by my name I'm more JS based). 

Any ideas?
