### ISSUE TITLE
[Bug] Various Errors using Spleeter Seperate with custom model. 

### ISSUE THREAD

**Issue by JavaShipped** [deezer/spleeter#394]
## Description
I was originally having another [issue](https://github.com/deezer/spleeter/issues/390), but with help from @romi1502 that was resolved nicely. 

However, as soon as that issue was fixed, I immediately got thrown several other issues.

## Step to reproduce

I managed to run the seperate command with my custom model, and it thought about it for a long time and powershell was eating up my CPU, so it was doing something.

I used the following spleeter imput command: `spleeter separate -i 'F:\BluRay 5.1\Done\S01E01 - Ambush\fullmix.wav' -o output -p F:\SpleetTest\Configs\filmModel.json`

## Output
After about 30-40 seconds I got the error: 

```
Traceback (most recent call last):
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: F:/SpleetTest/Configs/filmModel\model.ckpt-0.data-00000-of-00001 : The system cannot find the file specified.
; No such file or directory
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: F:/SpleetTest/Configs/filmModel\model.ckpt-0.data-00000-of-00001 : The system cannot find the file specified.
; No such file or directory
         [[node save/RestoreV2 (defined at c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\joe93\AppData\Local\Programs\Python\Python37\Scripts\spleeter.exe\__main__.py", line 9, in <module>
    sys.exit(entrypoint())
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 228, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 195, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 180, in _separate_librosa
    sess = self._get_session()
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 158, in _get_session
    saver = tf.train.Saver()
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1695, in restore_v2
    name=name)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\joe93\AppData\Local\Programs\Python\Python37\Scripts\spleeter.exe\__main__.py", line 9, in <module>
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 228, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 195, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 180, in _separate_librosa
    sess = self._get_session()
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 161, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

NewRandomAccessFile failed to Create/Open: F:/SpleetTest/Configs/filmModel\model.ckpt-0.data-00000-of-00001 : The system cannot find the file specified.
; No such file or directory
         [[node save/RestoreV2 (defined at c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\joe93\AppData\Local\Programs\Python\Python37\Scripts\spleeter.exe\__main__.py", line 9, in <module>
    sys.exit(entrypoint())
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 228, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 195, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 180, in _separate_librosa
    sess = self._get_session()
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 158, in _get_session
    saver = tf.train.Saver()
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1695, in restore_v2
    name=name)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "c:\users\joe93\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

```
I have so little experience with tensor, I don't know where to begin. From a few searches, this looks like a tensor issue with defining the parameters of the input (the sound files).

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 (fully updated) |
| Installation type |  pip  |
| RAM available     | 16GB  |
| Hardware spec     | RTX2080 / Ryzen R2600 |

**Comment by JavaShipped** [comment]
The main error I'm getting at the moment is this: 

`ValueError: Cannot feed value of shape (25836, 2, 6) for Tensor 'mix_stft:0', which has shape '(?, 2049, 2)'`

I can't work out why, any help?

**Comment by Mahmoussam** [comment]
I have the same problem now :(
Win10
installed using conda 
8GB ram 
GTX 1650 /intel HD
` C:\Users\princ\Documents\spleeter>python -m spleeter separate -i workspace/audio.wav -p spleeter:2stems -o myoutput
Traceback (most recent call last):
  File "C:\Users\princ\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\princ\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\princ\Documents\spleeter\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\princ\Documents\spleeter\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\princ\Documents\spleeter\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\princ\Documents\spleeter\spleeter\commands\separate.py", line 36, in entrypoint
    separator.separate_to_file(
  File "C:\Users\princ\Documents\spleeter\spleeter\separator.py", line 310, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\Users\princ\Documents\spleeter\spleeter\separator.py", line 271, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\Users\princ\Documents\spleeter\spleeter\separator.py", line 248, in _separate_librosa
    outputs = sess.run(
  File "C:\Users\princ\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\princ\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1154, in _run
    raise ValueError(
ValueError: Cannot feed value of shape (25844, 2, 6) for Tensor 'mix_stft:0', which has shape '(None, 2049, 2)'`
i am trying to remove music from a movie according to this [tutorial](https://gist.github.com/dannguyen/58db5ac1866e8c930b2f2840a455653d)

**Comment by mmoussallam** [comment]
Hi @Mahmoussam 

This kind of error suggest that the audio is not loaded correctly (or that your wav file is empty). Is the path `workspace/audio.wav` correct relative to where you execute the command ?

**Comment by Mahmoussam** [comment]
Hi @mmoussallam .
Thanks for your reply :D .
my dir is : 
 ```spleeter:
		-workspace folder
		-etc folders
		-spleeter files
```

**Comment by mmoussallam** [comment]
Alright so I guess the file is there :) 
Your issue is with the standard `spleeter` model or with a custom one ?

**Comment by Mahmoussam** [comment]
standard one . 
i tried again now with the audio file in spleeter dir 
`C:\Users\princ\Documents\spleeter>python -m spleeter separate -i audio.wav -p spleeter:5stems -o myoutput
Traceback (most recent call last):
  File "C:\Users\princ\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\princ\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\princ\Documents\spleeter\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\princ\Documents\spleeter\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\princ\Documents\spleeter\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\princ\Documents\spleeter\spleeter\commands\separate.py", line 36, in entrypoint
    separator.separate_to_file(
  File "C:\Users\princ\Documents\spleeter\spleeter\separator.py", line 310, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\Users\princ\Documents\spleeter\spleeter\separator.py", line 271, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\Users\princ\Documents\spleeter\spleeter\separator.py", line 248, in _separate_librosa
    outputs = sess.run(
  File "C:\Users\princ\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\princ\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1154, in _run
    raise ValueError(
ValueError: Cannot feed value of shape (25844, 2, 6) for Tensor 'mix_stft:0', which has shape '(None, 2049, 2)'
`

**Comment by mmoussallam** [comment]
hmm ok, and you're spleeter version is up to date ?

**Comment by Mahmoussam** [comment]
@mmoussallam  yes

**Comment by mmoussallam** [comment]
alright and does it also happen with the `audio_example.mp3` file ?

**Comment by Mahmoussam** [comment]
No it doesn't,it worked perfectly.

**Comment by mmoussallam** [comment]
Ok so it's definitely an issue with your audio file :) how long is it and how many channels ?

**Comment by Mahmoussam** [comment]
How to find these details?

**Comment by Mahmoussam** [comment]
@mmoussallam  so? maybe you didn't notice this thread

**Comment by AaronPeng920** [comment]
The source code is wrong till now.

**Comment by Lucicy** [comment]
Did anyone solve this error? Thanks

**Comment by Lucicy** [comment]
This is due to the the channels of audio, i got the 5.1 type audio, it has 6 channels. First to convert to 2 channels, then execute.
