### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by vkharatmal** [deezer/spleeter#398]
## Description

When ever I try to run this command: "python -m spleeter separate -i audio_example.mp3 -p spleeter:4stems -o output" I get error as :

FileNotFoundError: [WinError 2] The system cannot find the file specified.

I tried running this in conda as well as VCS but no success.

## Step to reproduce

1.Cloned repository in VSC
2.Installed dependencies through requirements.txt as using given command.
3.Could not run test as make was coming as invalid command.
4.Input file(audio_example.mp3) was already in folder so I directly ran command "python -m spleeter separate -i audio_example.mp3 -p spleeter:4stems -o output"

## Output

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Git projects\Spleeter\spleeter\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "D:\Git projects\Spleeter\spleeter\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "D:\Git projects\Spleeter\spleeter\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "D:\Git projects\Spleeter\spleeter\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "D:\Git projects\Spleeter\spleeter\spleeter\separator.py", line 227, in separate_to_file
    sample_rate=self._sample_rate)
  File "D:\Git projects\Spleeter\spleeter\spleeter\audio\ffmpeg.py", line 72, in load
    probe = ffmpeg.probe(path)
  File "D:\Git projects\Spleeter\spleeterenv\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 |
| Installation type | pip             |
| Hardware spec     | CPU i-7        |

## Additional context

NA

**Comment by mmoussallam** [comment]
Hi @vkharatmal 

You need to have a valid ffmpeg installation before using spleeter.

**Comment by vkharatmal** [comment]
Isnt that is already included in requirements.txt? and I have checked if its installed, its already there.
