### ISSUE TITLE
[Bug] Unable to install via Conda

### ISSUE THREAD

**Issue by Akashic101** [deezer/spleeter#400]
## Description

While installing spleeter multiple times via Conda the installer failed everytime while examaining conflicts

## Step to reproduce

1: Either `conda install -c conda-forge spleeter` or `conda install -c conda-forge spleeter-gpu`. Running the window as an administrator makes no difference, it always results in an error

## Output

```bash
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\David\anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\Users\David\anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "C:\Users\David\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError:
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.

    conda config --set unsatisfiable_hints True


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\David\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\Users\David\anaconda3\lib\site-packages\conda\cli\install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "C:\Users\David\anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "C:\Users\David\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "C:\Users\David\anaconda3\lib\site-packages\conda\models\match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Users\David\anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Users\David\anaconda3\lib\site-packages\conda\models\match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "C:\Users\David\anaconda3\lib\site-packages\conda\models\match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ C:\Users\David\anaconda3\Scripts\conda-script.py install -c conda-forge spleeter-gpu`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\David\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\David\anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\David\anaconda3
                 HOMEPATH=\Users\David
      MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared
                          Libraries\compiler\lib\mic
                     PATH=C:\Users\David\anaconda3;C:\Users\David\anaconda3\Library\mingw-w64\bi
                          n;C:\Users\David\anaconda3\Library\usr\bin;C:\Users\David\anaconda3\Li
                          brary\bin;C:\Users\David\anaconda3\Scripts;C:\Users\David\anaconda3\bi
                          n;C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin;C:\Python38\
                          Scripts\;C:\Python38\;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system
                          32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowe
                          rShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files
                          (x86)\WinSCP\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\Common Files\Autodesk
                          Shared\;C:\Program Files\FileBot\;C:\Program
                          Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft
                          SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL
                          Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program
                          Files\PuTTY\;C:\Program Files (x86)\M6 Securities\Humble Trove
                          Downloader\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\lib\mpv
                          .install\tools;C:\Program Files\dotnet\;C:\Program Files\doxygen\bin;C
                          :\Users\David\anaconda3;C:\Users\David\anaconda3\Library\mingw-w64\bin
                          ;C:\Users\David\anaconda3\Library\usr\bin;C:\Users\David\anaconda3\Lib
                          rary\bin;C:\Users\David\anaconda3\Scripts;C:\Users\David\AppData\Local
                          \Programs\Python\Python38-32\Scripts\;C:\Users\David\AppData\Local\Pro
                          grams\Python\Python38-32\;C:\Users\David\AppData\Local\Microsoft\Windo
                          wsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition
                          2019.3\bin;C:\Program Files\JetBrains\PyCharm Community Edition
                          2019.3\bin;C:\Program Files\JetBrains\PhpStorm 2019.3\bin;C:\FFmpeg\bi
                          n\;C:\Users\David\AppData\Roaming\npm;C:\Users\David\AppData\Local\Pro
                          grams\Microsoft VS Code\bin;C:\Users\David\.dotnet\tools
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\David\.condarc
 populated config files :
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : C:\Users\David\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\David\anaconda3\pkgs
                          C:\Users\David\.conda\pkgs
                          C:\Users\David\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\David\anaconda3\envs
                          C:\Users\David\.conda\envs
                          C:\Users\David\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | Conda|
| RAM available     | 8,9/16GB|
| Hardware spec     | Nvidia 1060 6GB / Ryzen 6 3600 / |

## Additional context

Running `pip install spleeter` results into 
```
ERROR: Could not find a version that satisfies the requirement spleeterpip (from versions: none)
ERROR: No matching distribution found for spleeterpip
```

**Comment by swimmesberger** [comment]
Getting the same issue on Windows 10 with anaconda.

**Comment by mojontwins** [comment]
Same here. Did a clean Anaconda install even, same results.

**Comment by akhil-ghatiki** [comment]
facing the same issue in mac os.

**Comment by Sockrocker** [comment]
I got literally exactly the same error report on Windows 10, after doing a clean re-install of Anaconda.
