### ISSUE TITLE
[Bug] When running spleeter it says that: it cannot find the input file however it is there

### ISSUE THREAD

**Issue by EllyasOuasti** [deezer/spleeter#403]
Traceback (most recent call last):
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\Scripts\spleeter.exe\__main__.py", line 9, in <module>
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 227, in separate_to_file
    sample_rate=self._sample_rate)
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\spleeter\audio\ffmpeg.py", line 72, in load
    probe = ffmpeg.probe(path)
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\xxx\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by vkharatmal** [comment]
I have same issue. But there is one command given by one of member here and that did work for me perfectly. 
Still dont know why this error. Please provide more clarification if you got any answer.

**Comment by EllyasOuasti** [comment]
Well, I installed spleeter, tensor, ffmpeg....
went to the location of the song I wanna get its vocals, run the command:
`python -m spleeter separate -i eminem_musicbox.mp3 -o eminem`
and it gave me the error mentioned, also tried the same one without "python -m", still no success. which command worked 4 you

**Comment by vkharatmal** [comment]
https://github.com/deezer/spleeter/issues/380#issue-621284486
You can find the working model with just one cmd line.
Great work by this guy!

**Comment by CapsAdmin** [comment]
This error is related to ffmpeg-python not being able to find the ffmpeg binaries and not the file input.

The error is very misleading in this case though, I was confused about the same thing when I tried to get it working.
