### ISSUE TITLE
tensroflow unable to load compat

### ISSUE THREAD

**Issue by medcelerate** [deezer/spleeter#429]
## Description
When installing spleeter it appears one of the package dependencies is out of sync with the requirements of the conda repo. Spleeter doesn't run and produces an error when trying to load a tensorflow module
## Step to reproduce

Run:
```
conda install -c conda-forge spleeter
spleeter separate -i <file> -o
```
1. Installed using `conda`
2. Run as `Any user`

## Output

```bash
```
File "/Users/djevanclark/.spconda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 33, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/Users/djevanclark/.spconda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 53, in <module>
    from tensorflow_estimator.python.estimator import util as estimator_util
  File "/Users/djevanclark/.spconda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/util.py", line 75, in <module>
    class _DatasetInitializerHook(tf.compat.v1.train.SessionRunHook):
AttributeError: module 'tensorflow' has no attribute 'compat'
```
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS |
| Installation type | Conda            |
| RAM available     | 16Gb                             |
| Hardware spec     | i7 AMD 560    |

**Comment by Christilut** [comment]
I'm seeing the same thing here on a High Sierra mac.

ps: You should name your bug

```
Traceback (most recent call last):
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 58, in <module>
    entrypoint()
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 36, in main
    enable_logging()
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/spleeter/utils/logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/spleeter/utils/logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 36, in <module>
    from tensorflow._api.v1 import compat
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow_core/_api/v1/compat/__init__.py", line 23, in <module>
    from tensorflow._api.v1.compat import v1
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow_core/_api/v1/compat/v1/__init__.py", line 672, in <module>
    from tensorflow_estimator.python.estimator.api._v1 import estimator
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 33, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 53, in <module>
    from tensorflow_estimator.python.estimator import util as estimator_util
  File "/var/folders/g3/x105jlz10hv45zkys924j7vr0000gn/T/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/util.py", line 75, in <module>
    class _DatasetInitializerHook(tf.compat.v1.train.SessionRunHook):
AttributeError: module 'tensorflow' has no attribute 'compat'

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12) {
```

**Comment by Christilut** [comment]
Reverting back to 1.4.9 solved the issue.

Maybe [this](https://github.com/tensorflow/tensorflow/issues/37525#issuecomment-598480859) can help us in the latest version?

**Comment by themcclure** [comment]
@Christilut I was just going to draw attention to that ticket.

Installing conda on a fresh machine `import tensorflow` gives the same error. So it's not spleeter specific.

`conda upgrade tensorflow` shows that spleeter has a dependency on a specific version
`Updating tensorflow is constricted by 
spleeter -> requires tensorflow==1.15`

Which is the version I have installed.
Tensorflow 2.1 apparently resolves this, though that looks like a lot of work to patch in...

**Comment by themcclure** [comment]
Can confirm that @Christilut workaround worked for me too.
Took a couple of tries to figure out the command:

`conda install -c conda-forge spleeter=1.4.9`

**Comment by chenei** [comment]
Hi,
This is also reproduce in macOS Catalina 10.15.3

**Comment by bscout9956** [comment]
This should have been name. Can reproduce on Windows 10 as seen above.

**Comment by romi1502** [comment]
I updated the conda package.
The installation of spleeter with conda should be back to normal: 
```bash
conda install -c conda-forge spleeter
```
The "AttributeError: module 'tensorflow' has no attribute 'compat'" error should no longer appear.
