### ISSUE TITLE
[Bug] Can't run spleeter separate because of ModuleNotFoundError

### ISSUE THREAD

**Issue by MyNameIsRene** [deezer/spleeter#453]
## Description

I get a ModuleNotFoundError: No module named numba.decorators when running the separate command.
I have Version 4.8.2 of Anaconda and i have set up the installation in a fresh environment. I have also tried to use a different numba version, since i read somewhere that there is a problem with the decorators in 0.50. I still got the same error.

## Step to reproduce

1. Installed using Conda 4.8.2
2. Run spleeter separate -i audio.mp3 -p spleeter:2stems -o output
3. Got ModuleNotFound: No module named 'numba.decorators' error

## Output

```bash
(py37) D:\Music\Spleeter>spleeter separate -i audio.mp3 -p spleeter:2stems -o output
Traceback (most recent call last):
  File "C:\Users\Rene\anaconda3\envs\py37\Scripts\spleeter-script.py", line 10, in <module>
    sys.exit(entrypoint())
  File "C:\Users\Rene\anaconda3\envs\py37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\Rene\anaconda3\envs\py37\lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\Rene\anaconda3\envs\py37\lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\Rene\anaconda3\envs\py37\lib\site-packages\spleeter\separator.py", line 23, in <module>
    from librosa.core import stft, istft
  File "C:\Users\Rene\anaconda3\envs\py37\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\Rene\anaconda3\envs\py37\lib\site-packages\librosa\core\__init__.py", line 109, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\Rene\anaconda3\envs\py37\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\Rene\anaconda3\envs\py37\lib\site-packages\librosa\util\__init__.py", line 71, in <module>
    from . import decorators
  File "C:\Users\Rene\anaconda3\envs\py37\lib\site-packages\librosa\util\decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows  |
| Installation type | Conda              |
| RAM available     | 8GB                             |
| Hardware spec     | NVidia 1050ti / Intel I5 3570k           |

**Comment by mcpower** [comment]
I personally encountered the same problem, and I worked around it with `conda install numba==0.45.0`. Perhaps #347 is related?

**Comment by MyNameIsRene** [comment]
@mcpower Oh my goodness, this actually worked. Thank you so much.
