### ISSUE TITLE
[Bug] "ModuleNotFoundError: No module named 'numba.decorators'" on fresh install

### ISSUE THREAD

**Issue by judilsteve** [deezer/spleeter#458]
## Description

Attempting to run the example spleeter command in the readme results in an import error.

Seems to be related to using an [old version of librosa](https://github.com/librosa/librosa/issues/1160)

## Step to reproduce

1. Install miniconda 4.8.3 x64 for Windows
2. Install spleeter via `conda create --name spleeter -c conda-forge spleeter`
3. Activate spleeter environment via `conda activate spleeter`
4. Attempt to run spleeter via `spleeter separate -i '[redacted]' -p spleeter:2stems -o [redacted]`

## Output

```
(spleeter) PS C:\Users\[redacted]> spleeter separate -i '[redacted]' -p spleeter:2stems -o [redacted]
Traceback (most recent call last):
  File "C:\Users\[redacted]\miniconda3\envs\spleeter\Scripts\spleeter-script.py", line 10, in <module>
    sys.exit(entrypoint())
  File "C:\Users\[redacted]\miniconda3\envs\spleeter\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\[redacted]\miniconda3\envs\spleeter\lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\[redacted]\miniconda3\envs\spleeter\lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\[redacted]\miniconda3\envs\spleeter\lib\site-packages\spleeter\separator.py", line 23, in <module>
    from librosa.core import stft, istft
    from . import core
  File "C:\Users\[redacted]\miniconda3\envs\spleeter\lib\site-packages\librosa\core\__init__.py", line 109, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\[redacted]\miniconda3\envs\spleeter\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\[redacted]\miniconda3\envs\spleeter\lib\site-packages\librosa\util\__init__.py", line 71, in <module>
    from . import decorators
  File "C:\Users\[redacted]\miniconda3\envs\spleeter\lib\site-packages\librosa\util\decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows|
| Installation type | Conda|
| RAM available     | 16GB                             |
| Hardware spec     | GTX1660/i5 6600K  |

**Comment by mmoussallam** [comment]
Hi @judilsteve 

This is a known problem with the latest `librosa` package: https://github.com/librosa/librosa/issues/1204 you probably need to downgrade  your `numba` package with `pip install numba==0.48`

**Comment by judilsteve** [comment]
@mmoussallam Thanks, this worked but I had to use the `--ignore-installed` flag to stop pip complaining. Hopefully this thread helps others with the same issue.

**Comment by mevsme** [comment]
why the hell to recommend use conda to install spleeter if then you need install additional packages with pip???

**Comment by Thanhcaro** [comment]
It's really make me headache too. Haizzz
