### ISSUE TITLE
[Discussion] It's possible to use pipe with Spleeter

### ISSUE THREAD

**Issue by Slidix99** [deezer/spleeter#466]
I'm on Ubuntu and i've videos files.
I will know if it's possible to use the pipes with Spleeter because i want, firstly, convert my video files in wav format and after that use the pipeline with Spleeter and re-use a pipe to create waveforms.
For the moment, i'm trying that : 

`ffmpeg -i myFile.mp4 -f wav - | spleeter separate -i -  -p spleeter:2stems -o separated`

but i've errors like that: 

Traceback (most recent call last):
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/site-packages/spleeter/audio/ffmpeg.py", line 108, in save
    os.makedirs(directory)
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'separated/-'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/l2-rd4/workspace/anaconda3/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/site-packages/spleeter/commands/separate.py", line 45, in entrypoint
    separator.join()
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/site-packages/spleeter/separator.py", line 68, in join
    task.get()
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/site-packages/spleeter/audio/ffmpeg.py", line 108, in save
    os.makedirs(directory)
  File "/home/l2-rd4/workspace/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'separated/-'
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
size=    1304kB time=00:00:06.93 bitrate=1540.9kbits/s speed=0.204x    
video:0kB audio:1308kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

I can do the commands separately but with pipes I've problems . So if you have solutions, I'm listening.
Thanks!

**Comment by Faylixe** [comment]
Hello and thank you for your suggestion.

Indeed, pipe are not supported as we do not read data from stdin but from file only. One solution for your problem would be to use an intermediate file.

Although I feel like this would be indeed a nice feature to add (through a `--stdin` parameter). So we will probably consider it in the future.

**Comment by Slidix99** [comment]
Nice,
Thank you for your reply

**Comment by vadd98** [comment]
Hi, is there any news about the use of pipe with Spleeter?

**Comment by Vicopem01** [comment]
Hi, any update regarding pipes?
