### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 404000** [deezer/spleeter#467]
(base) C:\Users\DESKTOP\Desktop\spleeter-master>spleeter separate -i exemple.mp3 -p spleeter:2stems -o output
Traceback (most recent call last):
  File "C:\Users\DESKTOP\miniconda3\Scripts\spleeter-script.py", line 10, in <module>
    sys.exit(entrypoint())
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\spleeter\separator.py", line 228, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\spleeter\separator.py", line 195, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\spleeter\separator.py", line 180, in _separate_librosa
    sess = self._get_session()
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\spleeter\separator.py", line 161, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by techxel** [comment]
same problem!

**Comment by techxel** [comment]
@404000   I created the output folder first, then succeed

**Comment by 404000** [comment]
The method did not work for me

**Comment by damingwangguan** [comment]
我也碰到了这个问题，然后发现是因为 model文件问题。
如果想要解决，自己下载需要的model.tar.gz文件。解压到操作目录的pretrained_models/2stems 中
下面是例子：
pretrained_models/2stems/checkpoint
pretrained_models/2stems/model.data-00000-0f-00001
pretrained_models/2stems/model.index
pretrained_models/2stems/model.meta
