### ISSUE TITLE
Used conda to install, doesn't work

### ISSUE THREAD

**Issue by mevsme** [deezer/spleeter#468]
````
Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\envs\py36\Scripts\spleeter-script.py", line 9, in <module>
    sys.exit(entrypoint())
  File "C:\Users\admin\miniconda3\envs\py36\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\admin\miniconda3\envs\py36\lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\admin\miniconda3\envs\py36\lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\admin\miniconda3\envs\py36\lib\site-packages\spleeter\separator.py", line 23, in <module>
    from librosa.core import stft, istft
  File "C:\Users\admin\miniconda3\envs\py36\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\admin\miniconda3\envs\py36\lib\site-packages\librosa\core\__init__.py", line 109, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\admin\miniconda3\envs\py36\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\admin\miniconda3\envs\py36\lib\site-packages\librosa\util\__init__.py", line 71, in <module>
    from . import decorators
  File "C:\Users\admin\miniconda3\envs\py36\lib\site-packages\librosa\util\decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'
````

I used conda to install spleeter, I installed librosa and numba, still doesn't work 😡 

````
conda activate spleeter
Could not find conda environment: spleeter
You can list all discoverable environments with `conda info --envs`.

Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.
At C:\Users\admin\miniconda3\shell\condabin\Conda.psm1:101 char:36
+         Invoke-Expression -Command $activateCommand;
+                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Invo
   keExpressionCommand
````

````
 conda install -c numba numba
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
`````

**Comment by mmoussallam** [comment]
HI @mevsme ,

This was actually a `librosa` issue described [there](https://github.com/librosa/librosa/issues/1105) and that should be fixed now with the newest librosa version.
