### ISSUE TITLE
I used pip to install Spleeter, it doesn't work

### ISSUE THREAD

**Issue by mevsme** [deezer/spleeter#469]
So I ditched conda and used python installer and installed it and pip.

````
pip install spleeter
Requirement already satisfied: spleeter in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages
Requirement already satisfied: ffmpeg-python in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from spleeter)
Requirement already satisfied: norbert==0.2.1 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from spleeter)
Requirement already satisfied: pandas==0.25.1 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from spleeter)
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from spleeter)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from spleeter)
Requirement already satisfied: librosa==0.7.2 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from spleeter)
Requirement already satisfied: numba==0.48.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from spleeter)
Requirement already satisfied: tensorflow==1.15.2 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from spleeter)
Requirement already satisfied: importlib_resources in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from spleeter)
Requirement already satisfied: future in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from ffmpeg-python->spleeter)
Requirement already satisfied: scipy in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from norbert==0.2.1->spleeter)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from pandas==0.25.1->spleeter)
Requirement already satisfied: numpy>=1.13.3 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from pandas==0.25.1->spleeter)
Requirement already satisfied: pytz>=2017.2 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from pandas==0.25.1->spleeter)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from requests->spleeter)
Requirement already satisfied: idna<3,>=2.5 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from requests->spleeter)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from requests->spleeter)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from requests->spleeter)
Requirement already satisfied: audioread>=2.0.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from librosa==0.7.2->spleeter)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from librosa==0.7.2->spleeter)
Requirement already satisfied: joblib>=0.12 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from librosa==0.7.2->spleeter)
Requirement already satisfied: decorator>=3.0.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from librosa==0.7.2->spleeter)
Requirement already satisfied: six>=1.3 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from librosa==0.7.2->spleeter)
Requirement already satisfied: resampy>=0.2.2 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from librosa==0.7.2->spleeter)
Requirement already satisfied: soundfile>=0.9.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from librosa==0.7.2->spleeter)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from numba==0.48.0->spleeter)
Requirement already satisfied: google-pasta>=0.1.6 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: astor>=0.6.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: wrapt>=1.11.1 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: keras-applications>=1.0.8 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: absl-py>=0.7.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: tensorflow-estimator==1.15.1 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: gast==0.2.2 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: tensorboard<1.16.0,>=1.15.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorflow==1.15.2->spleeter)
Requirement already satisfied: zipp>=0.4; python_version < "3.8" in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from importlib_resources->spleeter)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa==0.7.2->spleeter)
Requirement already satisfied: cffi>=1.0 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from soundfile>=0.9.0->librosa==0.7.2->spleeter)
Requirement already satisfied: h5py in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from keras-applications>=1.0.8->tensorflow==1.15.2->spleeter)
Requirement already satisfied: markdown>=2.6.8 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.2->spleeter)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.2->spleeter)
Requirement already satisfied: pycparser in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from cffi>=1.0->soundfile>=0.9.0->librosa==0.7.2->spleeter)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.2->spleeter)
You are using pip version 9.0.1, however version 20.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
````

But when I try `spleeter separate -i audio_example.mp3 -p spleeter:2stems -o output` I get

````
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Scripts\spleeter-script.py", line 33, in <module>
    sys.exit(load_entry_point('spleeter==1.5.4', 'console_scripts', 'spleeter')())
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
```

Why is it happening?

**Comment by mmoussallam** [comment]
Hi again @mevsme 

Not sure what's happening here but it seems your python environment is a bit messed up. I'd recommend starting from a clean [virtualenv](https://docs.python.org/3.6/tutorial/venv.html)

Good luck
