### ISSUE TITLE
[Bug] Running stops after a while

### ISSUE THREAD

**Issue by ItId123** [deezer/spleeter#480]
## Description

Hi,

While training Spleeter, I got an error after a few thousands steps (occurs after 6000-12000 steps).
The error is: 
(0) Unknown: Failed to WriteFile: cache/training_0.data-00000-of-00001.tempstate12880671843826882180 : There is not enough space on the disk.
; Unknown error
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_3133]]

## Step to reproduce

1. Installed using 
- conda install -c conda-forge spleeter-gpu==1.5.3
- conda install numba==0.48
- pip install librosa==0.7.2
2. Run "__main__.py"  (via pyCharm) with parameters : train -p configs/myConfig.json -d "C:\Users\myUserName\myDB"
3. Got the  error above

## Output
INFO:spleeter:Loading audio b'C:\\Users\\myUserName\\myDB\\train/7740/mixture.wav' from 23.853846153846156 to 43.853846153846156
INFO:spleeter:Loading audio b'C:\\Users\\myUserName\\myDB\\train/7235/vocals.wav' from 17.76153846153846 to 37.761538461538464
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Loading audio b'C:\\Users\\myUserName\\myDB\\train/6461/drums.wav' from 4.561538461538461 to 24.56153846153846
INFO:spleeter:Loading audio b'C:\\Users\\myUserName\\myDB\\train/3288/bass.wav' from 17.76153846153846 to 37.761538461538464
INFO:spleeter:Loading audio b'C:\\Users\\myUserName\\myDB\\train/1355/mixture.wav' from 2.5307692307692307 to 22.53076923076923
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
Traceback (most recent call last):
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to WriteFile: cache/training_0.data-00000-of-00001.tempstate12880671843826882180 : There is not enough space on the disk.
; Unknown error
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_3133]]
  (1) Unknown: Failed to WriteFile: cache/training_0.data-00000-of-00001.tempstate12880671843826882180 : There is not enough space on the disk.
; Unknown error
	 [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/myUserName/Anaconda3/pkgs/spleeter-gpu-1.5.3-py_0/site-packages/spleeter/__main__.py", line 58, in <module>
    entrypoint()
  File "C:/Users/myUserName/Anaconda3/pkgs/spleeter-gpu-1.5.3-py_0/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:/Users/myUserName/Anaconda3/pkgs/spleeter-gpu-1.5.3-py_0/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\spleeter\commands\train.py", line 98, in entrypoint
    evaluation_spec)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 473, in train_and_evaluate
    return executor.run()
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 613, in run
    return self.run_local()
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to WriteFile: cache/training_0.data-00000-of-00001.tempstate12880671843826882180 : There is not enough space on the disk.
; Unknown error
	 [[node IteratorGetNext (defined at \Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
	 [[IteratorGetNext/_3133]]
  (1) Unknown: Failed to WriteFile: cache/training_0.data-00000-of-00001.tempstate12880671843826882180 : There is not enough space on the disk.
; Unknown error
	 [[node IteratorGetNext (defined at \Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'IteratorGetNext':
  File "/Users/myUserName/Anaconda3/pkgs/spleeter-gpu-1.5.3-py_0/site-packages/spleeter/__main__.py", line 58, in <module>
    entrypoint()
  File "/Users/myUserName/Anaconda3/pkgs/spleeter-gpu-1.5.3-py_0/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/Users/myUserName/Anaconda3/pkgs/spleeter-gpu-1.5.3-py_0/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\spleeter\commands\train.py", line 98, in entrypoint
    evaluation_spec)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 473, in train_and_evaluate
    return executor.run()
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 613, in run
    return self.run_local()
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1188, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1025, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_estimator\python\estimator\util.py", line 65, in parse_input_fn_result
    result = iterator.get_next()
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 426, in get_next
    name=name)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2518, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "\Users\myUserName\Anaconda3\envs\run_11_8\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

Process finished with exit code 1

## Environment

|                              |                                                         |
| ------------------- | -------------------------------------- |
| OS                        | Windows                                          | 
| Installation type   | Conda / pip (librosa only)                |
| RAM available      | 32GB                                                |
| Hardware spec     | GPU NVIDIA GeForce RTX 2080 Ti   |

**Comment by romi1502** [comment]
The error `There is not enough space on the disk` is rather self explanatory: you're lacking disk space for caching spectrogram while training.
In the training phase, spleeter caches input and output spectrograms to disk to avoid recomputing them at each epoch, so you need enough disk space to store all your dataset spectrograms (which can be big, depending on the size of your dataset). 
You can avoid caching by not setting "training_cache" in the JSON config file, but be aware that it will be very inefficient make training much longer so it is definitely not an acceptable solution.
Another solution would be to take spectrograms computation out from the tensorflow dataset pipeline and to perform the spectrograms computation on GPU (which would add a bit but limited amount of overhead) but it is not implemented in spleeter and will require some extra work.

**Comment by ItId123** [comment]
Hi 

Thanks for the quick response.
What you meant is that I need a free disk space which is much greater than the dataset size, right?
(I have ~ 20GB free disk space, while musDB size is 29 GB)

Thanks
