### ISSUE TITLE
[Bug] Can't running Spleeter as a Python Module on Windows 10 Pycharm "Python Console".

### ISSUE THREAD

**Issue by RiskySignal** [deezer/spleeter#499]
I think it's probably a small problem with Unix file paths.

System Version: Windows 10 1903.
IDE: PyCharm 2020.2.2 (Professional Edition)

Problem:
I can run spleeter everywhere except in Python Console of Pycharm (Windows 10). When I ran the script `Separator("spleeter-2stems-16kHz")`, I got this error information:

`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda\Anaconda3\envs\py36-tf\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\Anaconda3\envs\py36-tf\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Anaconda\Anaconda3\envs\py36-tf\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda\Anaconda3\envs\py36-tf\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Anaconda\Anaconda3\envs\py36-tf\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "D:\Anaconda\Anaconda3\envs\py36-tf\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'D:\\workspace\\Phantom-of-Formants\\<input>'
`

And I'm sure I have downloaded the model proporly, so I guess it might be the Unix File Path problem.

**Comment by mmoussallam** [comment]
Hi @RiskySignal 

There's a typo in your code it's `Separator('spleeter:2stems-16kHz')` that works.
