### ISSUE TITLE
[Bug] can't separate: ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by eyehol3** [deezer/spleeter#509]
## Description

spleeter can't separate; throws an error

## Step to reproduce

1. Installed using `pip install spleeter`
2. Run as `python -m spleeter separate -i karooselb.mp3  -p spleeter:2stems -o output
` or `spleeter separate -i karooselb.mp3  -p spleeter:2stems -o output`
3. Got `ModuleNotFoundError: No module named '_lzma'` error

## Output

```bash
Traceback (most recent call last):
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/spleeter/__main__.py", line 58, in <module>
    entrypoint()
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/spleeter/__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/spleeter/commands/separate.py", line 15, in <module>
    from ..separator import Separator
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/spleeter/separator.py", line 27, in <module>
    from librosa.core import stft, istft
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/librosa/util/__init__.py", line 84, in <module>
    from .files import *  # pylint: disable=wildcard-import
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/librosa/util/files.py", line 11, in <module>
    import pooch
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/pooch/__init__.py", line 7, in <module>
    from .processors import Unzip, Untar, Decompress
  File "/Users/qwerty/Music/spleeter/spleeterenv/lib/python3.7/site-packages/pooch/processors.py", line 8, in <module>
    import lzma
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS  |
| Installation type |  pip              |
|RAM available | 16GB|

**Comment by mmoussallam** [comment]
Hi @eyehol3 

According to this: https://github.com/pandas-dev/pandas/issues/27532 it seems to be an issue with your python setup (since lzma is part of the standard python lib).

Hope this helps
