### ISSUE TITLE
Deleted pretrained_models folder and now it tracebacks when redownloading

### ISSUE THREAD

**Issue by Simon818** [deezer/spleeter#514]
I was cleaning up my home directory and deleted the pretrained_models folder a while ago. Now when I run Spleeter I get the traceback below. I'm not sure if this is user error or not. I solved it by manually downloading and extracting the models, so this isn't a blocker or anything.

C:\Users\Simon Jaeger>c:\python37\python -m spleeter separate -o spleeter -p spleeter:2stems -i test.flac
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python37\lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "c:\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\python37\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "c:\python37\lib\site-packages\spleeter\separator.py", line 310, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "c:\python37\lib\site-packages\spleeter\separator.py", line 271, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "c:\python37\lib\site-packages\spleeter\separator.py", line 247, in _separate_librosa
    sess = self._get_session()
  File "c:\python37\lib\site-packages\spleeter\separator.py", line 228, in _get_session
    get_default_model_dir(self._params['model_dir']))
  File "c:\python37\lib\site-packages\spleeter\utils\estimator.py", line 25, in get_default_model_dir
    return model_provider.get(model_dir)
  File "c:\python37\lib\site-packages\spleeter\model\provider\__init__.py", line 67, in get
    model_directory)
  File "c:\python37\lib\site-packages\spleeter\model\provider\github.py", line 97, in download
    with requests.get(url, stream=True) as response:
AttributeError: __enter__

**Comment by romi1502** [comment]
Hello @Simon818 ,
this seems to be an error with the `requests` package that is used for downloading the models.
It may be linked to the version of `requests` you're using. Check this SO post and let us know if it solves the issue: https://stackoverflow.com/questions/56719749/why-am-i-getting-the-error-atributeerror-enter-when-using-requests-get-i
