### ISSUE TITLE
spleeter.separator not found when installing with pip

### ISSUE THREAD

**Issue by SebastianCardenasEscoto** [deezer/spleeter#548]
## Description

Pip installing seems to be missing the separator module.

## Step to reproduce

1. Pip installed ffmpeg and spleeter
2. Ran this code
```
from spleeter.separator import Separator

sep = Separator('spleeter:2stems')
path = "C:\\Users\\Sebastian\\Documents\\VScode\\Personal Projects\\Music Recognition Project"
song_path = path + "Automatic Stop.mp3" 

sep.separate_to_file(song_path,path)`
```

3. Got this error `ImportError: DLL load failed: The specified module could not be found.` 

## Output

```
2021-01-04 20:05:42.196029: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-01-04 20:05:42.201066: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "c:/Users/Sebastian/Documents/VScode/Personal Projects/Music Recognition Project/pokesong2.py", line 1, in <module>
    from spleeter.separator import Separator
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\spleeter\separator.py", line 27, in <module>
    from librosa.core import stft, istft
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\util\__init__.py", line 87, in <module>
    from ._nnls import *  # pylint: disable=wildcard-import
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\util\_nnls.py", line 13, in <module>
    import scipy.optimize
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\optimize\__init__.py", line 389, in <module>
    from .optimize import *
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\Users\Sebastian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: The specified module could not be found.
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | pip |
| RAM available     | 20GB  |   
| Hardware spec     | GTX 1060 / i5 6600k |
| Python version |     3.8.0 |

**Comment by romi1502** [comment]
Hi @SebastianCardenasEscoto
The issue seems to be an incorrect installation of scipy or an incorrect environment setting for accessing dynamic libraries used by scipy and then does not seem to be a spleeter issue.
Please check [https://stackoverflow.com/questions/22753695/dll-load-failed-with-scipy-optimize](https://stackoverflow.com/questions/22753695/dll-load-failed-with-scipy-optimize) as it is seems to be a very similar issue.
