### ISSUE TITLE
[Bug] NotImplementedError when performing separation

### ISSUE THREAD

**Issue by carter-king** [deezer/spleeter#581]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description
I am getting "NotImplementedError: Cannot convert a symbolic Tensor (strided_slice_4:0) to a numpy array." when trying to call separate_to_file(). I get the same error when trying to separate a file using the command line.

## Step to reproduce

I installed spleeter using conda. As I said above I also tried using the basic commands for the command line. I am passing a file path for the audio source and a path for the output location. I tried the same thing with the corresponding Python API instructions from the wiki and got the same error.
## Output
2021-02-16 11:57:56.454178: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From /Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    main('/Users/carterking/Maxflow/spleeter-component/spleeter/audio_example.mp3', '/Users/carterking/Maxflow/spleeter-component/audio_example_OUTPUT.mp3')
  File "main.py", line 21, in main
    separator.separate_to_file(filePath,savePath,audio_loader)
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/separator.py", line 228, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/separator.py", line 195, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/separator.py", line 173, in _separate_librosa
    outputs = self._get_builder().outputs
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/model/__init__.py", line 301, in outputs
    self._build_outputs()
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/model/__init__.py", line 476, in _build_outputs
    self._outputs = self.masked_stfts
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/model/__init__.py", line 325, in masked_stfts
    self._build_masked_stfts()
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/model/__init__.py", line 440, in _build_masked_stfts
    for instrument, mask in self.masks.items():
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/model/__init__.py", line 319, in masks
    self._build_masks()
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/model/__init__.py", line 423, in _build_masks
    instrument_mask = self._extend_mask(instrument_mask)
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/spleeter/model/__init__.py", line 397, in _extend_mask
    mask_shape[-1]))
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2338, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2295, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/Users/carterking/miniconda3/envs/spleeter-env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (strided_slice_4:0) to a numpy array.

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                |MacOS|
| Installation type | Conda|
| RAM available     |8Gb|
| Hardware spec     |CPU|

**Comment by romi1502** [comment]
Hello @carter-king,
There seems to be indeed an issue with the conda installation on Mac OS (which by the way doesn't install the latest version of spleeter).
Installing the latest version with pip should solve the issue:
```bash
pip install spleeter --upgrade
```

**Comment by carter-king** [comment]
Hello @romi1502,
I ran that upgrade inside my projects conda env and it fixed the error. Thanks for the help!
