### ISSUE TITLE
httpcore.ReadTimeout and httpx.ReadTimeout When trying to download pretrained model

### ISSUE THREAD

**Issue by foderking** [deezer/spleeter#621]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

I always get a timeout error when it tries to download 5 pretrain model data

## Step to reproduce

1. Ran  `spleeter separate -o audio_output -p spleeter:5stems-16kHz rand.mp3`

## Output

```bash
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/5stems.tar.gz
Traceback (most recent call last):
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpx\_exceptions.py", line 326, in map_exceptions
    yield
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpx\_models.py", line 1214, in iter_raw
    for part in self.stream:
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpcore\_sync\connection_pool.py", line 61, in __iter__
    for chunk in self.stream:
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpcore\_bytestreams.py", line 45, in __iter__
    for chunk in self._iterator:
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpcore\_sync\http2.py", line 387, in body_iter
    event = self.connection.wait_for_event(self.stream_id, timeout)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpcore\_sync\http2.py", line 198, in wait_for_event
    self.receive_events(timeout)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpcore\_sync\http2.py", line 205, in receive_events
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpcore\_backends\sync.py", line 62, in read
    return self.sock.recv(n)
  File "c:\users\foderking\.conda\envs\spleeter\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\foderking\.conda\envs\spleeter\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\foderking\.conda\envs\spleeter\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Foderking\.conda\envs\spleeter\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\spleeter\__main__.py", line 128, in separate
    separator.separate_to_file(
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\spleeter\separator.py", line 382, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\spleeter\separator.py", line 325, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\spleeter\separator.py", line 269, in _separate_librosa
    sess = self._get_session()
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\spleeter\separator.py", line 241, in _get_session
    model_directory: str = provider.get(self._params["model_dir"])
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\spleeter\model\provider\__init__.py", line 80, in get
    self.download(model_directory.split(sep)[-1], model_directory)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\spleeter\model\provider\github.py", line 145, in download
    for chunk in response.iter_raw():
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpx\_models.py", line 1216, in iter_raw
    yield part
  File "c:\users\foderking\.conda\envs\spleeter\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\foderking\.conda\envs\spleeter\lib\site-packages\httpx\_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadTimeout: The read operation timed out
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | pip             |
| RAM available     | 8                           |
| Hardware spec     | Integrated Graphics/ Intel i5 - 2430M           |

**Comment by romi1502** [comment]
Hi @foderking 
This seems to be indeed a downloading issue. Can you double check that you can actually reach github.com from the shell where you launch spleeter? 
You can also try downloading manually the model from https://github.com/deezer/spleeter/releases/download/v1.4.0/5stems.tar.gz (using for instance `wget`) and put it in the directory of MODEL_PATH (which default to ./pretrained_models)

**Comment by foderking** [comment]
Thanks. redownloading the models manually fixed the issue
