### ISSUE TITLE
[Bug] Spleeter Separate on custom trained model tries to download another model

### ISSUE THREAD

**Issue by andresC98** [deezer/spleeter#626]
## Description

I have trained a custom model and the separate function does not work as intended as it tries to download the model from a nonexisting url.

## Step to reproduce

1. Created custom model training data / specs annotated in the custom_model_config.json
2. Trained model (succesfully, apparently) using `!spleeter train -p "custom_model_config.json" -d "PathToCustomDataset"`. I check that the trained model folder is created.
3. When trying to separate a file using `!spleeter separate -o sep_out -p "custom_model_config.json" "test.mp3"`

The function tries to download the model from a url which obviously does not exists. Why is this happening?

## Output

```
tcmalloc: large alloc 1694474240 bytes == 0x556df36f0000 @  0x7f9e527bf1e7 0x7f9e4ef5f631 0x7f9e4efc3cc8 0x7f9e4efc3de3 0x7f9e4f061ed8 0x7f9e4f062734 0x7f9e4f062882 0x556d45843f68 0x7f9e4efaf53d 0x556d45841c47 0x556d45841a50 0x556d458b5453 0x556d458b04ae 0x556d458433ea 0x556d458b232a 0x556d458b04ae 0x556d458433ea 0x556d458b160e 0x556d4584330a 0x556d458b160e 0x556d458b04ae 0x556d458433ea 0x556d458b160e 0x556d458b04ae 0x556d458433ea 0x556d458b232a 0x556d458b04ae 0x556d45782e2c 0x556d458b2bb5 0x556d458b07ad 0x556d45782e2c
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/bach10_model_2.tar.gz
Traceback (most recent call last):
  File "/usr/local/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.7/dist-packages/spleeter/__main__.py", line 256, in entrypoint
    spleeter()
  File "/usr/local/lib/python3.7/dist-packages/typer/main.py", line 214, in _call_
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in _call_
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/spleeter/__main__.py", line 137, in separate
    synchronous=False,
  File "/usr/local/lib/python3.7/dist-packages/spleeter/separator.py", line 382, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "/usr/local/lib/python3.7/dist-packages/spleeter/separator.py", line 325, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "/usr/local/lib/python3.7/dist-packages/spleeter/separator.py", line 269, in _separate_librosa
    sess = self._get_session()
  File "/usr/local/lib/python3.7/dist-packages/spleeter/separator.py", line 241, in _get_session
    model_directory: str = provider.get(self._params["model_dir"])
  File "/usr/local/lib/python3.7/dist-packages/spleeter/model/provider/__init__.py", line 80, in get
    self.download(model_directory.split(sep)[-1], model_directory)
  File "/usr/local/lib/python3.7/dist-packages/spleeter/model/provider/github.py", line 141, in download
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/httpx/_models.py", line 1103, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 404 Client Error: Not Found for url: https://github.com/deezer/spleeter/releases/download/v1.4.0/bach10_model_2.tar.gz
For more information check: https://httpstatuses.com/404
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                |  Linux (Colab environment) |
| Installation type |  pip              |
| RAM available     | 16GB                             |

**Comment by GelflingHand** [comment]
It appears that you need to move your model to the pretrained_models folder after you've trained it in order for the separate command to be able to find it.

**Comment by andresC98** [comment]
Where should be that pretrained_models folder? I cannot find it

**Comment by andresC98** [comment]
> It appears that you need to move your model to the pretrained_models folder after you've trained it in order for the separate command to be able to find it.

Where should be that pretrained_models folder? I cannot find it

**Comment by GelflingHand** [comment]
I think it's created automatically when you run separate without specifying a custom model, and it downloads the default 2stems. You should be able to just create it manually in the same folder as your config.json file.

**Comment by andresC98** [comment]
@GelflingHand perfect! I have been able to load a custom pretrained model from such folder, and now this issue is solved. Thanks!
