### ISSUE TITLE
[Bug] Won't write to output folder

### ISSUE THREAD

**Issue by jeeneeus** [deezer/spleeter#639]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

When adding the -o command, Spleeter gives me an error and won't run properly. However, if I omit the -o command, Spleeter will run, but create the files in a temp folder

## Step to reproduce
executing `spleeter separate -o output -p spleeter:4stems /input/audio_example.mp3` won't work
executing `spleeter separate -p spleeter:4stems /input/audio_example.mp3` does work, but creates files in C:\Users\User\AppData\Local\Temp\separated_audio

## Output

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\spleeter\__main__.py", line 128, in separate
    separator.separate_to_file(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\spleeter\separator.py", line 383, in separate_to_file
    self.save_to_file(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\spleeter\separator.py", line 448, in save_to_file
    os.makedirs(directory)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'output'
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | pip            |
| RAM available     | 16GB                          |
| Hardware spec     | N/A |

**Comment by romi1502** [comment]
Hi @jeeneeus,
It seems your system cannot create properly the `output` folder when exporting the file.
I haven't tested on windows, but it works properly on MacOS and Linux, so it may be a Windows specific issue. Have you tried to create the directory `output` before running spleeter? also, have you tried using an absolute path to the directory instead of a relative one ?

**Comment by jeeneeus** [comment]
Hey @romi1502. I tried creating the output folder before running spleeter and using an absolute path to the directory for the output. Neither worked.

I did glean new information though. When the output folder is created first, the error says the file in output\audio_example (without .mp3, even though command includes it) was not found. So it seems that it is trying to find the file within the output folder. I can't change the directory and move the file inside the output folder because then I end up at the original issue where the (new) output can't be found. I also tried copying the file into the output folder, but to no avail.

I'm not sure why it is doing this, but it makes sense as to why if I omit the -o command, it works. It won't try to find the file within the output folder since there is no output mentioned.
