### ISSUE TITLE
save_path error while using API[Bug][windows]

### ISSUE THREAD

**Issue by Coder-Pranav** [deezer/spleeter#656]
### Issue
Api giving save_path error even though destination path is mentioned

### Code

```
from spleeter.separator import Separator

separator = Separator('spleeter:2stems')
separator.separate_to_file('./song.wav',
                           destination='./output')
```

### Error Log

Traceback (most recent call last):
  File "D:/Work/Python/test/extract.py", line 4, in <module>
    separator.separate_to_file('D:/Work/Python/test/song.wav',
  File "D:\Work\conda_env\music\lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "D:\Work\conda_env\music\lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "D:\Work\conda_env\music\lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "D:\Work\conda_env\music\lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "D:\Work\conda_env\music\lib\site-packages\tensorflow\python\training\saver.py", line 1291, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by romi1502** [comment]
Hi @Coder-Pranav,
this does not seem to be linked to the destination path, but to the path where the model is supposed to be stored. 
The default path where  the model are stored is `./pretrained_models` (otherwise, you can set it with the `MODEL_PATH` env variable).
Can you check that the model was correctly downloaded and that you indeed have a `./pretrained_models/2stems` path with some files in it? 
If the model wasn't downloaded properly, you can try to download it manually from https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz and put it in `./pretrained_models/`.

I was not able to reproduce you bug on Linux, so it could be a Windows specific issue (that may be linked to the latest release). What is the spleeter version you use?

**Comment by Coder-Pranav** [comment]
Yes thank you, you are right it was the issue with the model.
