### ISSUE TITLE
How do you install it?

### ISSUE THREAD

**Issue by Lemm99** [deezer/spleeter#687]
From https://github.com/deezer/spleeter#quick-start

"It can be done on most platform using Conda:"
"Note that we no longer recommend using conda for installing spleeter."

?????? 

Gotta love open source projects and their wonderful documentation.

**Comment by Lemm99** [comment]
and from https://github.com/deezer/spleeter/issues/423

"Conda which remains the recommended way to install spleeter."

So, how do you install it on say Ubuntu, or Mint?

**Comment by Ionys320** [comment]
`pip install spleeter` ;-)

**Comment by BrunoDSL** [comment]
And how do you make sure the dependencies are satisfied? There's no alternative for installing them other than the one that's not recommended.

**Comment by Zipdox** [comment]
The easiest way is to use python pip.

First, use pip3 to remove every tensorflow package if you have any installed, because python will shit itself over versions. Do the same for grpcio.

Then, just install spleeter with pip3, and it should resolve all dependencies.

**Comment by BrunoDSL** [comment]
> The easiest way is to use python pip.
> 
> First, use pip3 to remove every tensorflow package if you have any installed, because python will shit itself over versions. Do the same for grpcio.
> 
> Then, just install spleeter with pip3, and it should resolve all dependencies.

Sure. Spleeter doesn't work on Python 3.10. Spleeter-GPU doesn't work on Python 3.9. I don't think pip will help you with any of that. The wiki doesn't say anything. You have to look on PyPI. I'd personally remove the wiki entry for installation or improve it, because it's not helpful at all.

**Comment by erika-r** [comment]
so do you still need to install conda to use it or can you just use pip?

**Comment by Zipdox** [comment]
Create a VENV

**Comment by bgenchel** [comment]
python 3.11.7 via pyenv
MacOS Sonoma 14.1

`>> pip install spleeter`
```
Collecting spleeter
  Obtaining dependency information for spleeter from https://files.pythonhosted.org/packages/10/0b/1ee10015ae2269c1cd1ae5439ae8d48d8680dd984638b4b787d1e4ce4e6b/spleeter-2.1.0-py3-none-any.whl.metadata
  Using cached spleeter-2.1.0-py3-none-any.whl.metadata (10 kB)
Collecting ffmpeg-python==0.2.0 (from spleeter)
  Obtaining dependency information for ffmpeg-python==0.2.0 from https://files.pythonhosted.org/packages/d7/0c/56be52741f75bad4dc6555991fabd2e07b432d333da82c11ad701123888a/ffmpeg_python-0.2.0-py3-none-any.whl.metadata
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Collecting httpx[http2]<0.17.0,>=0.16.1 (from spleeter)
  Obtaining dependency information for httpx[http2]<0.17.0,>=0.16.1 from https://files.pythonhosted.org/packages/2d/c6/59aa4188e7eddb9e89ec67a51598ca6bfc09f1b38c9b45f7ee45af7a4df4/httpx-0.16.1-py3-none-any.whl.metadata
  Using cached httpx-0.16.1-py3-none-any.whl.metadata (38 kB)
Collecting librosa==0.8.0 (from spleeter)
  Using cached librosa-0.8.0.tar.gz (183 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting norbert==0.2.1 (from spleeter)
  Obtaining dependency information for norbert==0.2.1 from https://files.pythonhosted.org/packages/22/85/1e4f09c84d28b5541a4a8eece320902c4d2fa264dfe51f779548396f0fea/norbert-0.2.1-py2.py3-none-any.whl.metadata
  Using cached norbert-0.2.1-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting numpy<1.19.0,>=1.16.0 (from spleeter)
  Using cached numpy-1.18.5.zip (5.4 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-install-k5hpkjw6/numpy_35727bac9d5e4bcbb6351e7d96580bce/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-install-k5hpkjw6/numpy_35727bac9d5e4bcbb6351e7d96580bce/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-install-k5hpkjw6/numpy_35727bac9d5e4bcbb6351e7d96580bce/tools/cythonize.py", line 238, in <module>
          main()
        File "/private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-install-k5hpkjw6/numpy_35727bac9d5e4bcbb6351e7d96580bce/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-install-k5hpkjw6/numpy_35727bac9d5e4bcbb6351e7d96580bce/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-install-k5hpkjw6/numpy_35727bac9d5e4bcbb6351e7d96580bce/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-install-k5hpkjw6/numpy_35727bac9d5e4bcbb6351e7d96580bce/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/Users/benjamingenchel/.pyenv/versions/3.11.7/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/benjamingenchel/.pyenv/versions/3.11.7/envs/parts_order_3.11/bin/python3.11', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/Users/benjamingenchel/.pyenv/versions/3.11.7/envs/parts_order_3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/benjamingenchel/.pyenv/versions/3.11.7/envs/parts_order_3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/benjamingenchel/.pyenv/versions/3.11.7/envs/parts_order_3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-build-env-yzr5gvtz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-build-env-yzr5gvtz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/9h/qs_8jb3n117711821rsrr0p80000gn/T/pip-build-env-yzr5gvtz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
```
