### ISSUE TITLE
[Bug] Cannot install, spleeter wants llvmlite 0.36.0 while pulling in numba that wants llvmlite 0.37.0

### ISSUE THREAD

**Issue by ell1e** [deezer/spleeter#698]
- [X] I didn't find a similar issue already open.
- [ ] I read the documentation (README AND Wiki)
- [X] I have installed FFMpeg
- [X] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

```
$ python3.7 -m spleeter separate -p spleeter:2stems -o output inneruniverse.mp3 
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 262, in <module>
    entrypoint()
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 256, in entrypoint
    spleeter()
  File "/usr/local/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 114, in separate
    from .separator import Separator
  File "/usr/local/lib/python3.7/site-packages/spleeter/separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "/usr/local/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.7/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/usr/local/lib/python3.7/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.7/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.7/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/usr/local/lib64/python3.7/site-packages/numba/__init__.py", line 197, in <module>
    _ensure_llvm()
  File "/usr/local/lib64/python3.7/site-packages/numba/__init__.py", line 109, in _ensure_llvm
    raise ImportError(msg)
ImportError: Numba requires at least version 0.37.0 of llvmlite.
Installed version is 0.36.0.
Please update llvmlite.
```

```
$ sudo python3.7 -m pip install -U llvmlite==0.37.0
Collecting llvmlite==0.37.0
  Downloading https://files.pythonhosted.org/packages/55/21/f7df5d35f3f5d0637d64a89f6b0461f2adf78e22916d6372486f8fc2193d/llvmlite-0.37.0.tar.gz (125kB)
    97% |███████████████████████████████▏| 122kB 49kB/s eta 0:00    100% |████████████████████████████████| 133kB 49kB/s 
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  Complete output from command /usr/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7r17xd2s/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-m1g2weyd --python-tag cp37:
  running bdist_wheel
  /usr/bin/python3.7 /tmp/pip-install-7r17xd2s/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-7r17xd2s/llvmlite/ffi/build.py", line 220, in <module>
      main()
    File "/tmp/pip-install-7r17xd2s/llvmlite/ffi/build.py", line 210, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-7r17xd2s/llvmlite/ffi/build.py", line 134, in main_posix
      raise RuntimeError(msg) from None
  RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
  error: command '/usr/bin/python3.7' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
spleeter 2.3.0 has requirement llvmlite<0.37.0,>=0.36.0, but you'll have llvmlite 0.37.0 which is incompatible.
```

## Step to reproduce

1. Install using `python3.7 -m pip` on Fedora 35
2. End up with above

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                |  Fedora Linux 35 |
| Installation type | pip            |
| RAM available     |                              |
| Hardware spec     | skylake laptop cpu      |

**Comment by thomper** [comment]
For a temporary workaround, you can downgrade numba to 0.53.0 and llvmlite to 0.36.0.  Best to do this in a venv if you weren't already.  On Ubuntu 20.04:
```
pip3 install -U numba==0.53.0
pip3 install -U llvmlite==0.36.0
```

**Comment by romi1502** [comment]
Hi @ell1e,
It may not be related, but I remember having this error with a not up-to-date version of `pip` (that, for some reason, was doing weird things for dependency resolution). From what I remember, updating `pip` to the latest version would solve the issue.

**Comment by romi1502** [comment]
I can confirm that I have the same issue (incompatible numba and llvmlite version) when trying to install spleeter with `pip` 20.0.2 (default version install by `apt` in ubuntu) while the dependency resolution is done correctly with a more recent version of `pip` such as 21.3.1.
So the issue seems to be rather a `pip` resolution issue than a spleeter one.
