### ISSUE TITLE
[Bug] Failed to run spleeter

### ISSUE THREAD

**Issue by nagayev** [deezer/spleeter#708]
## Description

I have installed spleeter using README's method.
When I tried to run spleeter I get `ModuleNotFoundError: No module named 'llvmlite.binding.dylib'`.

## Step to reproduce

1. Installed using readme instruction.
2. Run as `spleeter separate -p spleeter:2stems -o output track.mp3`
3. Got `ModuleNotFoundError` error

## Output

```bash
Traceback (most recent call last):
  File "/home/marat/miniconda3/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/marat/miniconda3/lib/python3.9/site-packages/spleeter/__main__.py", line 256, in entrypoint
    spleeter()
  File "/home/marat/.local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/marat/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/marat/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/marat/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/marat/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/marat/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/marat/.local/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/marat/miniconda3/lib/python3.9/site-packages/spleeter/__main__.py", line 114, in separate
    from .separator import Separator
  File "/home/marat/miniconda3/lib/python3.9/site-packages/spleeter/separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "/home/marat/.local/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/marat/.local/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/marat/.local/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/marat/.local/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/marat/.local/lib/python3.9/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/marat/.local/lib/python3.9/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/home/marat/miniconda3/lib/python3.9/site-packages/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/home/marat/miniconda3/lib/python3.9/site-packages/numba/core/config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "/home/marat/.local/lib/python3.9/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
ModuleNotFoundError: No module named 'llvmlite.binding.dylib'
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Linux  |
| Installation type | pip             |
| RAM available     | 8                             |

**Comment by nagayev** [comment]
I read spleeter can't be run on Python 3.9.
I think it would be nice to see this warning at the README.

**Comment by romi1502** [comment]
Hi @nagayev,
Spleeter does support Python 3.9 now.
Your issue seems to be a llvmlite install issue. See for instance [https://stackoverflow.com/questions/28830418/issue-with-pythons-numba-no-module-llvmlite-binding](https://stackoverflow.com/questions/28830418/issue-with-pythons-numba-no-module-llvmlite-binding) that seems to describe the same issue. You'll need to fix your llvmlite install then.

**Comment by sudheervdm** [comment]
you must create a environment with conda  and set python3.8.8 as maximum 
code 
conda create -n {your environment name} python=3.8.8

after creating env you must type

conda activate {your env name}
examples :  conda create -n spleeter-new python=3.8.8 (for create)
conda activate spleeter-new (for activate env)

and run command in new env its look like starting your nv name in bracket after activated 
(spleeter-new) drive:/user/conda > 

so run 
conda install -c conda-forge ffmpeg libsndfile
after depencies collected run
pip install spleeter

lso required ffmpeg version is mention below Will upload here Soon)
ffmpeg version git-2019-11-01-53c21c2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191010
  
  done and don't forget to add ffmpeg in your environment variable section
