### ISSUE TITLE
[Bug] name your bug

### ISSUE THREAD

**Issue by romger49** [deezer/spleeter#721]
Hello !!

I managed to install spleeter on my debian 10 .
when i launch : 

- [ spleeter separate -p spleeter:2stems -o output audio_example.mp3] 

I have

- [Traceback (most recent call last):
  File "/home/romger/.local/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/romger/.local/lib/python3.9/site-packages/spleeter/__main__.py", line 256, in entrypoint
    spleeter()
  File "/home/romger/.local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/romger/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/romger/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/romger/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/romger/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/romger/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/romger/.local/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/romger/.local/lib/python3.9/site-packages/spleeter/__main__.py", line 114, in separate
    from .separator import Separator
  File "/home/romger/.local/lib/python3.9/site-packages/spleeter/separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "/home/romger/.local/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/romger/.local/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/romger/.local/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/romger/.local/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/romger/.local/lib/python3.9/site-packages/librosa/util/__init__.py", line 84, in <module>
    from .files import *  # pylint: disable=wildcard-import
  File "/home/romger/.local/lib/python3.9/site-packages/librosa/util/files.py", line 11, in <module>
    import pooch
  File "/home/romger/.local/lib/python3.9/site-packages/pooch/__init__.py", line 19, in <module>
    from .processors import Unzip, Untar, Decompress
  File "/home/romger/.local/lib/python3.9/site-packages/pooch/processors.py", line 14, in <module>
    import lzma
  File "/usr/local/lib/python3.9/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
 ]

I follow this post : 

[(https://github.com/pandas-dev/pandas/issues/27532 )]

However for install of spleeter I had install python3.9 with conpilation . Then my lzma install is not accept by python3.9 .

Thank for your help !!

Jérome

**Comment by dustyny** [comment]
This is not an issue with spleeter, it's a problem with your python installation.. When you compile your own python, you need to add to add in lzma... If you use a prebuilt python distribution the problem should go away..

You can also try installing lzma using apt, yum, etc..
