### ISSUE TITLE
[Bug] AttributeError: module 'resampy' has no attribute 'filters'

### ISSUE THREAD

**Issue by ivellios1988** [deezer/spleeter#726]
## Description

When I try using Spleeter in Windows 10, I get the following error message:

`AttributeError: module 'resampy' has no attribute 'filters'`

## Step to reproduce

1. Install Python on Windows
2. Open cmd.exe
3. Go to directory with test mp3 and `spleeter separate -p spleeter:2stems -o output my_song.mp3`

## Output

```
C:\Users\ivell\Desktop>spleeter separate -p spleeter:2stems -o output my_song.mp3
Traceback (most recent call last):
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ivell\AppData\Local\Programs\Python\Python38\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\spleeter\separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\librosa\core\__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "c:\users\ivell\appdata\local\programs\python\python38\lib\site-packages\librosa\core\audio.py", line 39, in <module>
    BW_BEST = resampy.filters.get_filter("kaiser_best")[2]
AttributeError: module 'resampy' has no attribute 'filters'
```

**Comment by ls-milkyway** [comment]
Try: **spleeter separate -o output my_song.mp3** instead of "spleeter separate -p spleeter:2stems -o output my_song.mp3" as default commands automatically uses 2 stems......plus I am also facing problems when using switch -d ...but default command (as mentioned) works.

**Comment by yasz** [comment]
still problems...
