### ISSUE TITLE
[Discussion] Trying to use my own training set but I get an error

### ISSUE THREAD

**Issue by dustyny** [deezer/spleeter#755]
I'm trying to use my own training set which is made up of 20 sec mono loops. I'm getting this error. I'm not sure if it's an issue with my data or the configuration that I'm using.  Any thoughts would be much appreciated, I've spent a lot of time on this. I can increase the duration of the loops I'm generating if that is needed. I'm including my config & the validation CSV to show my setup. 

Thank you very much for your help! 

`(spleeter) jupyter@drumsplit-trainer:~/data/drumsplit$ spleeter train -p config/drumsplit_config.json -d /home/jupyter/data/drumsplitter_training_loops/ --verbose
INFO:tensorflow:Using config: {'_model_dir': 'drumsplit_model', '_tf_random_seed': 3, '_save_summary_steps': 5, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.45
}
, '_keep_checkpoint_max': 2, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 10, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:spleeter:Start model training
INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps 1000 or save_checkpoints_secs None.
WARNING:tensorflow:From /opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/training/training_util.py:235: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Traceback (most recent call last):
  File "/opt/conda/envs/spleeter/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/spleeter/__main__.py", line 256, in entrypoint
    spleeter()
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/spleeter/__main__.py", line 89, in train
    tf.estimator.train_and_evaluate(estimator, train_spec, evaluation_spec)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/training.py", line 505, in train_and_evaluate
    return executor.run()
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/training.py", line 646, in run
    return self.run_local()
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/training.py", line 743, in run_local
    self._estimator.train(
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1201, in _train_model_default
    self._get_features_and_labels_from_input_fn(input_fn, ModeKeys.TRAIN))
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1037, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1130, in _call_input_fn
    return input_fn(**kwargs)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/spleeter/dataset.py", line 85, in get_training_dataset
    return builder.build(
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/spleeter/dataset.py", line 575, in build
    dataset = dataset.map(instrument.convert_to_uint)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1925, in map
    return MapDataset(self, map_func, preserve_cardinality=True)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4483, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3712, in __init__
    self._function = fn_factory()
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3134, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3100, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3687, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3617, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /opt/conda/envs/spleeter/lib/python3.8/site-packages/spleeter/dataset.py:194 convert_to_uint  *
        sample[self._spectrogram_key],
    /opt/conda/envs/spleeter/lib/python3.8/site-packages/spleeter/audio/convertor.py:110 spectrogram_to_db_uint  *
        db_spectrogram: tf.Tensor = gain_to_db(spectrogram)
    /opt/conda/envs/spleeter/lib/python3.8/site-packages/spleeter/audio/convertor.py:76 gain_to_db  *
        return 20.0 / np.log(10) * tf.math.log(tf.maximum(tensor, espilon))
    /opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py:5881 maximum  **
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /opt/conda/envs/spleeter/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:527 _apply_op_helper
        raise TypeError(

    TypeError: Expected uint8 passed to parameter 'y' of op 'Maximum', got 1e-09 of type 'float' instead. Error: Expected uint8, got 1e-09 of type 'float' instead.`

[drumsplit_validation.csv.txt](https://github.com/deezer/spleeter/files/8557553/drumsplit_validation.csv.txt)
[drumsplit_config.json.txt](https://github.com/deezer/spleeter/files/8557555/drumsplit_config.json.txt)

**Comment by dustyny** [comment]
I think I figured it out.. I accidently put the mixed.wav in instrument_list in the config
