### ISSUE TITLE
[Bug] protobuf & numba dependencies

### ISSUE THREAD

**Issue by DavidDoukhan** [deezer/spleeter#770]
- [X] I didn't find a similar issue already open.
- [X] I read the documentation (README AND Wiki)
- [X] I have installed FFMpeg
- [X] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

There were major change in protobuf since may 2022 (see [here](https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates)), that are not supported by the default pip installation method.

It seems currently necessary to downgrade protobuf and numba after spleeter's installation in order to use spleeter : 
`pip install protobuf==3.20.1 numba==0.53.0`

## Step to reproduce

1. Installed using 
```
virtualenv -p python3 env
source env/bin/activate
pip install spleeter
```

2. Run as `spleeter separate ~/mytest.wav`

3. Got `...` error

## Output

```
Traceback (most recent call last):
  File "/home/ddoukhan/env/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ddoukhan/env/lib/python3.8/site-packages/spleeter/__main__.py", line 256, in entrypoint
    spleeter()
  File "/home/ddoukhan/env/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/ddoukhan/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ddoukhan/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ddoukhan/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ddoukhan/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ddoukhan/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ddoukhan/env/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/ddoukhan/env/lib/python3.8/site-packages/spleeter/__main__.py", line 113, in separate
    from .audio.adapter import AudioAdapter
  File "/home/ddoukhan/env/lib/python3.8/site-packages/spleeter/audio/adapter.py", line 14, in <module>
    import tensorflow as tf
  File "/home/ddoukhan/env/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/ddoukhan/env/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/home/ddoukhan/env/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/ddoukhan/env/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/ddoukhan/env/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/ddoukhan/env/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/ddoukhan/env/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/ddoukhan/env/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/ddoukhan/env/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                |  Ubuntu 20.04.3 LTS -  5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Installation type | pip 20.0.2 with python 3.8.10     |
| RAM available     | 32 Go                             |
| Hardware spec     | Problems with GPU & CPU implementation of tensorflow             |

## Additional context

The following command after installation fix the behavior
```
pip install protobuf==3.20.1 numba==0.53.0
```

**Comment by d-dawg78** [comment]
Hi @DavidDoukhan ,

Thank you for letting us know about this issue. We have just released [Spleeter v2.3.1](https://github.com/deezer/spleeter/pull/771#issue-1263675643) to resolve it. Normally, `pip install spleeter` should work just fine, though please let us if this is not the case.

Happy Spleeting :))

**Comment by d-dawg78** [comment]
Hmm this is bizarre. Spleeter 2.3.1 was tested using Python 3.6, 3.7, 3.8, and 3.9 with a regular `pip install spleeter` followed by a `spleeter separate ...` command. The `numba` error you outline was never encountered. Can you try to clean up your `pip` (solutions found [here](https://stackoverflow.com/questions/11248073/what-is-the-easiest-way-to-remove-all-packages-installed-by-pip))? My intuition is that you have the wrong installation of `numba` already installed, and your `spleeter` installation defaults to using it (this issue is thus related to `pypi`). You can also try `pip install --force-reinstall --no-cache-dir spleeter`.

**Comment by DavidDoukhan** [comment]
Dear @d-dawg78 ,

Based on your advices, I reinstalled spleeter using the following commands : 
```bash
virtualenv -p python3 env
source env/bin/activate
pip install --force-reinstall --no-cache-dir spleeter
```
I obtained the same error message during installation than in my earlier attempts: 
```bash
ERROR: numba 0.55.2 has requirement llvmlite<0.39,>=0.38.0rc1, but you'll have llvmlite 0.36.0 which is incompatible.
```
I also obtained similar error messages than those obtained earlier

```bash
Traceback (most recent call last):
  File "/tmp/env/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/tmp/env/lib/python3.8/site-packages/spleeter/__main__.py", line 256, in entrypoint
    spleeter()
  File "/tmp/env/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/tmp/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/env/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/tmp/env/lib/python3.8/site-packages/spleeter/__main__.py", line 114, in separate
    from .separator import Separator
  File "/tmp/env/lib/python3.8/site-packages/spleeter/separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "/tmp/env/lib/python3.8/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/tmp/env/lib/python3.8/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/tmp/env/lib/python3.8/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/tmp/env/lib/python3.8/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/tmp/env/lib/python3.8/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/tmp/env/lib/python3.8/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/tmp/env/lib/python3.8/site-packages/numba/__init__.py", line 199, in <module>
    _ensure_llvm()
  File "/tmp/env/lib/python3.8/site-packages/numba/__init__.py", line 111, in _ensure_llvm
    raise ImportError(msg)
ImportError: Numba requires at least version 0.38.0 of llvmlite.
Installed version is 0.36.0.
Please update llvmlite.
```
I think this issue may be fixed by changing file the version of llvmlite to be used within file pyproject.toml .
I did a proposal which works fine on my machine in pull request #773

**Comment by d-dawg78** [comment]
Hi @DavidDoukhan ,

Thank you for your answer. We tried to reproduce your error on our end, but were unsuccessful doing so. More generally, conflicts between `numba` and `llvmlite` tend to be low-level and platform-specific. We'd like to avoid bumping the `llvmlite` version unless this problem becomes widespread in the Spleeter community.

We did however already get errors with these packages due to `pip`, and it seems like you are using an older version (20.0.2). Can you try to upgrade your `pip` to the latest version? This led us to solve the same problem that you are facing in [this issue](https://github.com/deezer/spleeter/issues/698).

**Comment by guess** [comment]
I am having this same issue. @DavidDoukhan have you found any resolution?

**Comment by mmoussallam** [comment]
We've done a bit of dependency cleaning in #785  so hopefully version 2.3.2 should not have this issue anymore.
