### ISSUE TITLE
MemoryError: Unable to allocate array with shape (307499, 2049, 2) and data type complex128

### ISSUE THREAD

**Issue by Florria2** [deezer/spleeter#836]
[D:\HDVideoConverterFactoryPro\Output\OutputVideo\Lamaternal.2022.Cast.5.1 WEBDL PESADA_track2_[spa]_DELAY 0ms.flac
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "E:\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "E:\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 260, in _separate_librosa
    stft = self._stft(waveform)
  File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 215, in _stft
    return np.concatenate(out, axis=2 - inverse)
  File "<__array_function__ internals>", line 6, in concatenate
MemoryError: Unable to allocate array with shape (307499, 2049, 2) and data type complex128

![图片](https://user-images.githubusercontent.com/128038240/225626844-70da40b2-143c-475e-afec-47fe1c3396b7.png)

An error occurred when extracting audio with a duration of 90 minutes. How to solve it?

**Comment by romi1502** [comment]
Hi @Florria2,
Spleeter is actually loading the full audio file at once for performing the separation, which is very memory intensive. So when you try to process a 90min files, it's very likely you're flooding the RAM of your computer.
So when you want to separate a large file, you'd better trim it in smaller slightly overlapping chunks, process them individually and then overlap and add the resulting chunks.
