### ISSUE TITLE
Spleeter(2.4.0) is not compatible with latest Flask version(2.2.2)

### ISSUE THREAD

**Issue by suraj143rosy** [deezer/spleeter#862]
Flask ==2.2.2
Spleeter == 2.4.0
Python >=3.7.3

I have tried using spleeter in a Flask service using the latest version of Flask. Unfortunately when i Import spleeter I am getting the below error. Upon resolving this error by installing the required version of click, i see that Flask is not running. How can we make spleeter to work with the latest version of Flask?

Error:
 **from spleeter.separator import Separator**
2023-07-27 11:43:14.011931: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-07-27 11:43:14.011974: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/vtp-vm-user/.local/lib/python3.7/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vtp-vm-user/.local/lib/python3.7/site-packages/spleeter/separator.py", line 30, in <module>
    from .audio.adapter import AudioAdapter
  File "/home/vtp-vm-user/.local/lib/python3.7/site-packages/spleeter/audio/adapter.py", line 20, in <module>
    from ..utils.logging import logger
  File "/home/vtp-vm-user/.local/lib/python3.7/site-packages/spleeter/utils/logging.py", line 12, in <module>
    from typer import echo
  File "/home/vtp-vm-user/.local/lib/python3.7/site-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/vtp-vm-user/.local/lib/python3.7/site-packages/click/termui.py)

**Comment by 372362092** [comment]
I also encountered the same problem

**Comment by 1731249586** [comment]
> I also encountered the same problem

Me, too. You got it?

**Comment by javaGH** [comment]
i had this and got it working.

i am not at the computer rught now so i cant look but the key was that deep down click and typer were conflicting.

i got it workjng with spleeter 2.0.2 or so and an older version of flask.
i put all errors in chatgpt until it worked :)

had also to downgrade python.

**Comment by pr-data-port** [comment]
any way how to get it working with specific versions of tensorflow-cpu or tensorflow? I am having the same problem, but the download time and space it occupies is not very efficient.
