### ISSUE TITLE
[Bug] It doesn't look like Python 3.11 is supported yet.

### ISSUE THREAD

**Issue by dragonjay-lyj** [deezer/spleeter#865]
- [√] I didn't find a similar issue already open.
- [√] I read the documentation (README AND Wiki)
- [√] I have installed FFMpeg
- [√] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

<img width="867" alt="77a525e9071f82fe4434deef0c95a2b2" src="https://github.com/deezer/spleeter/assets/111476039/3aa2d41c-b254-4ef1-8823-1d1447c20c0d">

## Step to reproduce

Follow the tutorial

## Output

pip install spleeter
Collecting spleeter
  Downloading spleeter-2.1.0-py3-none-any.whl (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.3/50.3 kB 852.7 kB/s eta 0:00:00
Collecting ffmpeg-python==0.2.0 (from spleeter)
  Downloading ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting httpx[http2]<0.17.0,>=0.16.1 (from spleeter)
  Downloading httpx-0.16.1-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.6/65.6 kB 1.8 MB/s eta 0:00:00
Collecting librosa==0.8.0 (from spleeter)
  Downloading librosa-0.8.0.tar.gz (183 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 2.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting norbert==0.2.1 (from spleeter)
  Downloading norbert-0.2.1-py2.py3-none-any.whl (11 kB)
Collecting numpy<1.19.0,>=1.16.0 (from spleeter)
  Downloading numpy-1.18.5.zip (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 893.6 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\tools\cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\tools\cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      warning: C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\numpy\__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\numpy\__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\numpy\__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\numpy\__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: _generator.pyx:3330:8: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\numpy\__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\numpy\__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              for i in range(1, RK_STATE_LEN):
                  self.rng_state.key[i] = val[i]
              self.rng_state.pos = i

              self._bitgen.state = &self.rng_state
              self._bitgen.next_uint64 = &mt19937_uint64
                                         ^
      ------------------------------------------------------------

      _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bit_generator.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Traceback (most recent call last):
        File "C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\tools\cythonize.py", line 238, in <module>
          main()
        File "C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\tools\cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\tools\cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\tools\cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "C:\Users\drago\AppData\Local\Temp\pip-install-yp351ez1\numpy_077ad87a9c86481e9850cbabee4e8f50\tools\cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "C:\Users\drago\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\drago\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "C:\Users\drago\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\drago\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\drago\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\drago\AppData\Local\Temp\pip-build-env-z51ki7yh\overlay\Lib\site-packages\setuptools\build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\drago\AppData\Local\Temp\pip-build-env-z51ki7yh\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\drago\AppData\Local\Temp\pip-build-env-z51ki7yh\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows                         |
| Installation type | pip                             |
| RAM available     | XGo                             |
| Hardware spec     | GPU                             |

**Comment by ALEXDINO7** [comment]
the same error i have with Python 3.11.4

**Comment by LLLKZY** [comment]
我从pypi上下载了spleeter的whl文件，可是却报错显示仅支持tensorflow版本小于2.10.0，大于等于2.5.0。
I downloaded the Spleter WHL file from pypi, but an error was reported indicating that only TensorFlow versions less than 2.10.0 and greater than or equal to 2.5.0 are supported.
我用7-zip打开了这个whl文件，并且查看了一个叫MEDATA的文件发现仅支持python版本>=3.7.1,<3.11所以无法支持python 3.11.x
I opened this whl file using 7-zip and checked a file called MEDATA and found that it only supports Python version>=3.7.1,<3.11, so it cannot support Python version 3.11. x
截图：
Screenshot:
![image](https://github.com/deezer/spleeter/assets/109969200/d3fa4ece-75c5-4aff-8514-c205bb0f11b8)
![image](https://github.com/deezer/spleeter/assets/109969200/e45f13e8-8ed4-4385-95cd-b486d2fab9a4)

**Comment by jbruneFei** [comment]
Same error Python 3.11.5

**Comment by jrgermain** [comment]
I can reproduce the error on macOS Ventura 13.4 (using Python 3.11.5).

Can also confirm that the install works fine after downgrading to 3.10.11.

**Comment by ericleigh007** [comment]
Disclaimer:
Not an expert
I was able to install here by creating a python 3.10 environment, then activating it, and installing there.
I used anaconda

```
conda create --name py310 python=3.10
conda activate py310
```

then installed the pre-reqs, and continued the installation as shown.

**Comment by nawed2611** [comment]
is there any way/process for it to make python 3.11 compatible?

**Comment by wenhq** [comment]
> Disclaimer: Not an expert I was able to install here by creating a python 3.10 environment, then activating it, and installing there. I used anaconda
> 
> ```
> conda create --name py310 python=3.10
> conda activate py310
> ```
> 
> then installed the pre-reqs, and continued the installation as shown.

numpy package must downgrade: 
conda create --name py310 python=3.10 numpy<2
conda activate py310
