### ISSUE TITLE
[Bug] Unable to install spleeter on Macbook running M1 chips because of old numpy version !!!

### ISSUE THREAD

**Issue by wptechnology** [deezer/spleeter#879]
- [X ] I didn't find a similar issue already open.
- [X ] I read the documentation (README AND Wiki)
- [X ] I have installed FFMpeg
- [X ] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

The error says that numpy no longer support long attribute.
And it is impossible to install 1.19.5 with Python 3.9

## Step to reproduce

Just try to install and run spleeter with python 3.9

## Output

.../Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
.../Library/Python/3.9/lib/python/site-packages/numba/types/__init__.py:110: FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.
  long_ = _make_signed(np.long)
Traceback (most recent call last):
  File ".../Library/Python/3.9/bin//spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File ".../Library/Python/3.9/lib/python/site-packages/spleeter/__main__.py", line 256, in entrypoint
    spleeter()
  File ".../Library/Python/3.9/lib/python/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File ".../Library/Python/3.9/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File ".../Library/Python/3.9/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File ".../Library/Python/3.9/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../Library/Python/3.9/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../Library/Python/3.9/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".../Library/Python/3.9/lib/python/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File ".../Library/Python/3.9/lib/python/site-packages/spleeter/__main__.py", line 114, in separate
    from .separator import Separator
  File ".../Library/Python/3.9/lib/python/site-packages/spleeter/separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File ".../Library/Python/3.9/lib/python/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File ".../Library/Python/3.9/lib/python/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File ".../Library/Python/3.9/lib/python/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File ".../Library/Python/3.9/lib/python/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File ".../Library/Python/3.9/lib/python/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File ".../Library/Python/3.9/lib/python/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File ".../Library/Python/3.9/lib/python/site-packages/numba/__init__.py", line 15, in <module>
    from . import config, errors, _runtests as runtests, types
  File ".../Library/Python/3.9/lib/python/site-packages/numba/types/__init__.py", line 110, in <module>
    long_ = _make_signed(np.long)
  File ".../Library/Python/3.9/lib/python/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS |
| Installation type | pip             |
| RAM available     | 64Go                             |
| Hardware spec     | Apple M1 Max             |

**Comment by bobsam** [comment]
> Do you have a solution now, please?

**Comment by TuanAnhNguyenCo** [comment]
I resolved this issue by installing Python 3.8.

**Comment by morenoh149** [comment]
I think 3.9 support was removed outright. This wont be fixed.
