### ISSUE TITLE
[Bug] name your bug

### ISSUE THREAD

**Issue by Test-Jim** [deezer/spleeter#899]
I used flask, and then called the interface. No error was reported the first time, but this error will definitely be reported the second time I called it.

Exception ignored in: <generator object Estimator.predict at 0x000001C3F2AF6AB0>
Traceback (most recent call last):
  File "C:\Users\admin123\PycharmProjects\sd_flask\.venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 618, in predict
    with tf.Graph().as_default() as g:
  File "C:\Users\admin123\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\admin123\PycharmProjects\sd_flask\.venv\lib\site-packages\tensorflow\python\framework\ops.py", line 5821, in get_controller
    with super(_DefaultGraphStack,
  File "C:\Users\admin123\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\admin123\PycharmProjects\sd_flask\.venv\lib\site-packages\tensorflow\python\framework\ops.py", line 5633, in get_controller
    raise AssertionError(
AssertionError: Nesting violated for default stack of <class 'tensorflow.python.framework.ops.Graph'> objects

**Comment by abellee** [comment]
me too

**Comment by venkatmacapp** [comment]
Same issue, Anyone find solution.

**Comment by Astronaut323** [comment]
我也遇到了这个问题

**Comment by chiwuyin** [comment]
me too

**Comment by chiwuyin** [comment]
In estimator.py add this,may resolve this problem.
tf.compat.v1.enable_eager_execution()  #jackyin
