### ISSUE TITLE
Configuration file configs/musdb_config.json not found

### ISSUE THREAD

**Issue by Uskhuu** [deezer/spleeter#90]
## Description

When tried to train it by musdb18, it saying the .json file is not found when it is clearly in that folder 

## Step to reproduce

1. Installed using `Anaconda`
2. Run as:  spleeter train -p configs/musdb_config.json -d /musdb
3. 
OSError: Configuration file configs/musdb_config.json not found

## Output

Traceback (most recent call last):
  File "c:\users\osoho\anaconda3\envs\spleeter-cpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\osoho\anaconda3\envs\spleeter-cpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\osoho\Anaconda3\envs\spleeter-cpu\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "c:\users\osoho\anaconda3\envs\spleeter-cpu\lib\site-packages\spleeter\__main__.py", line 47, in entrypoint
    main(sys.argv)
  File "c:\users\osoho\anaconda3\envs\spleeter-cpu\lib\site-packages\spleeter\__main__.py", line 40, in main
    params = load_configuration(arguments.params_filename)
  File "c:\users\osoho\anaconda3\envs\spleeter-cpu\lib\site-packages\spleeter\utils\configuration.py", line 45, in load_configuration
    raise IOError(f'Configuration file {descriptor} not found')
OSError: Configuration file configs/musdb_config.json not found

## Environment

 | Windows / Linux / MacOS / other |
| Installation type | Conda /|
| Hardware spec     | i5-7400 ; 8 GB ; NVIDIA GTX1050TI |           |

**Comment by Faylixe** [comment]
You are using a UNIX filesystem path. You are using Windows. So it would be `configs\musdb_config.json`.
