### ISSUE TITLE
[Feature] tell people how to run from git

### ISSUE THREAD

**Issue by ensonic** [deezer/spleeter#903]
## Description

Whike f3rr0-C47 tells you how to build from git it does not tell you how to run it. I am not here to learn yet another build system in depth and after glancing the poetry docs and trying e.g.
```
> poetry shell
The currently activated Python version 3.12.3 is not supported by the project (>=3.7.1,<3.11).
Trying to find and use a compatible version. 
Using python3.8 (3.8.19)
Spawning shell within /home/ensonic/.cache/pypoetry/virtualenvs/spleeter-_aolmB5c-py3.8
./spleeterenv/bin/spleeter --help
Traceback (most recent call last):
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ensonic/projects/audio/spleeter/./spleeterenv/bin/spleeter", line 33, in <module>
    sys.exit(load_entry_point('spleeter==2.0.2', 'console_scripts', 'spleeter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ensonic/projects/audio/spleeter/./spleeterenv/bin/spleeter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 982, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for spleeter
```

The binary install options don't work either. These days distros want you to use pipx, but that fails.
```
 pipx install spleeter
Fatal error from pip prevented installation. Full pip output in file:
    /home/ensonic/.local/pipx/logs/cmd_2024-08-04_13.56.45_pip_errors.log

pip seemed to fail to build package:
    numpy<1.19.0,>=1.16.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    subprocess.CalledProcessError: Command '['/home/ensonic/.local/pipx/venvs/spleeter/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
    RuntimeError: Running cythonize failed!
    error: metadata-generation-failed

Error installing spleeter.
```

**Comment by ensonic** [comment]
Now that I posted it I've found the answer, e.g.
```
poetry run spleeter separate --help
```

**Comment by yllekz** [comment]
The install appears to have broken on macOS as well, particularly with Apple Silicon chips. Trying to get Spleeter running per [this guide](https://memotut.com/simplest-windows-environment-for-spleeter-use-7281c/) seems to result in missing dependencies:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow=1.14.0*
  - python=3.7*
  - pandas==0.25.1
```
